In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/boston-crime-data/crime.csv


In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../input/boston-crime-data/crime.csv', encoding='latin-1')
df.head()

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


INCIDENT_NUMBER  OFFENSE_CODE  OFFENSE_CODE_GROUP  \
0      I182080058          2403  Disorderly Conduct   
1      I182080053          3201       Property Lost   
2      I182080052          2647               Other   
3      I182080051           413  Aggravated Assault   
4      I182080050          3122            Aircraft   

              OFFENSE_DESCRIPTION DISTRICT REPORTING_AREA SHOOTING  \
0            DISTURBING THE PEACE      E18            495      NaN   
1                 PROPERTY - LOST      D14            795      NaN   
2       THREATS TO DO BODILY HARM       B2            329      NaN   
3  ASSAULT - AGGRAVATED - BATTERY       A1             92      NaN   
4              AIRCRAFT INCIDENTS       A7             36      NaN   

      OCCURRED_ON_DATE  YEAR  MONTH DAY_OF_WEEK  HOUR    UCR_PART  \
0  2018-10-03 20:13:00  2018     10   Wednesday    20    Part Two   
1  2018-08-30 20:00:00  2018      8    Thursday    20  Part Three   
2  2018-10-03 19:20:00  2018     10   Wednesday    19    Part Two   
3  2018-10-03 20:00:00  2018     10   Wednesday    20    Part One   
4  2018-10-03 20:49:00  2018     10   Wednesday    20  Part Three   

         STREET        Lat       Long                     Location  
0  ARLINGTON ST  42.262608 -71.121186  (42.26260773, -71.12118637)  
1    ALLSTON ST  42.352111 -71.135311  (42.35211146, -71.13531147)  
2      DEVON ST  42.308126 -71.076930  (42.30812619, -71.07692974)  
3  CAMBRIDGE ST  42.359454 -71.059648  (42.35945371, -71.05964817)  
4   PRESCOTT ST  42.375258 -71.024663  (42.37525782, -71.02466343)

In [4]:
df = df.dropna(subset = ['Lat', 'Long'])
df = df[df['Lat'] > 0]
df

INCIDENT_NUMBER  OFFENSE_CODE  OFFENSE_CODE_GROUP  \
0           I182080058          2403  Disorderly Conduct   
1           I182080053          3201       Property Lost   
2           I182080052          2647               Other   
3           I182080051           413  Aggravated Assault   
4           I182080050          3122            Aircraft   
...                ...           ...                 ...   
327815   I050310906-00          3125     Warrant Arrests   
327816   I030217815-08           111            Homicide   
327817   I030217815-08          3125     Warrant Arrests   
327818   I010370257-00          3125     Warrant Arrests   
327819       142052550          3125     Warrant Arrests   

                        OFFENSE_DESCRIPTION DISTRICT REPORTING_AREA SHOOTING  \
0                      DISTURBING THE PEACE      E18            495      NaN   
1                           PROPERTY - LOST      D14            795      NaN   
2                 THREATS TO DO BODILY HARM       B2            329      NaN   
3            ASSAULT - AGGRAVATED - BATTERY       A1             92      NaN   
4                        AIRCRAFT INCIDENTS       A7             36      NaN   
...                                     ...      ...            ...      ...   
327815                       WARRANT ARREST       D4            285      NaN   
327816  MURDER, NON-NEGLIGIENT MANSLAUGHTER      E18            520      NaN   
327817                       WARRANT ARREST      E18            520      NaN   
327818                       WARRANT ARREST      E13            569      NaN   
327819                       WARRANT ARREST       D4            903      NaN   

           OCCURRED_ON_DATE  YEAR  MONTH DAY_OF_WEEK  HOUR    UCR_PART  \
0       2018-10-03 20:13:00  2018     10   Wednesday    20    Part Two   
1       2018-08-30 20:00:00  2018      8    Thursday    20  Part Three   
2       2018-10-03 19:20:00  2018     10   Wednesday    19    Part Two   
3       2018-10-03 20:00:00  2018     10   Wednesday    20    Part One   
4       2018-10-03 20:49:00  2018     10   Wednesday    20  Part Three   
...                     ...   ...    ...         ...   ...         ...   
327815  2016-06-05 17:25:00  2016      6      Sunday    17  Part Three   
327816  2015-07-09 13:38:00  2015      7    Thursday    13    Part One   
327817  2015-07-09 13:38:00  2015      7    Thursday    13  Part Three   
327818  2016-05-31 19:35:00  2016      5     Tuesday    19  Part Three   
327819  2015-06-22 00:12:00  2015      6      Monday     0  Part Three   

                   STREET        Lat       Long                     Location  
0            ARLINGTON ST  42.262608 -71.121186  (42.26260773, -71.12118637)  
1              ALLSTON ST  42.352111 -71.135311  (42.35211146, -71.13531147)  
2                DEVON ST  42.308126 -71.076930  (42.30812619, -71.07692974)  
3            CAMBRIDGE ST  42.359454 -71.059648  (42.35945371, -71.05964817)  
4             PRESCOTT ST  42.375258 -71.024663  (42.37525782, -71.02466343)  
...                   ...        ...        ...                          ...  
327815        COVENTRY ST  42.336951 -71.085748  (42.33695098, -71.08574813)  
327816           RIVER ST  42.255926 -71.123172  (42.25592648, -71.12317207)  
327817           RIVER ST  42.255926 -71.123172  (42.25592648, -71.12317207)  
327818  NEW WASHINGTON ST  42.302333 -71.111565  (42.30233307, -71.11156487)  
327819      WASHINGTON ST  42.333839 -71.080290  (42.33383935, -71.08029038)  

[306413 rows x 17 columns]

In [5]:
reporting_area_centers=df[~df["Long"].isna()].groupby("REPORTING_AREA")["Long","Lat"].mean().reset_index()
reporting_area_centers["geom"]=reporting_area_centers.loc[:,["Long","Lat"]].apply(lambda x: "POINT("+str(x["Long"])+" "+str(x["Lat"])+")",axis=1)
reporting_area_centers

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.


REPORTING_AREA       Long        Lat  \
0                  -71.079019  42.328928   
1                1 -70.996655  42.390179   
2               10 -71.008469  42.388751   
3              100 -71.054884  42.357810   
4              101 -71.054358  42.357237   
..             ...        ...        ...   
874            961 -71.125507  42.256711   
875            962 -71.072722  42.341868   
876             97 -71.058791  42.358096   
877             98 -71.057834  42.357567   
878             99 -71.056122  42.357940   

                                             geom  
0     POINT(-71.07901926097279 42.32892816517891)  
1     POINT(-70.99665524078951 42.39017944236842)  
2     POINT(-71.00846862046863 42.38875119562499)  
3     POINT(-71.05488435035824 42.35781029024798)  
4    POINT(-71.05435766527813 42.357236672872574)  
..                                            ...  
874   POINT(-71.12550696916665 42.25671135083332)  
875  POINT(-71.07272215000009 42.341867650000026)  
876   POINT(-71.05879099596038 42.35809580782488)  
877  POINT(-71.05783420354408 42.357566826483406)  
878  POINT(-71.05612151029125 42.357940040582555)  

[879 rows x 4 columns]

In [6]:
from sklearn.cluster import KMeans
from scipy.spatial.distance import cdist

In [7]:
clusterer = KMeans(n_clusters=500,random_state=0).fit(reporting_area_centers[["Long","Lat"]])
preds_1 = clusterer.predict(reporting_area_centers[["Long","Lat"]])

In [8]:
reporting_area_centers["cluster_no"]=preds_1
reporting_area_centers_clusters=reporting_area_centers.groupby("cluster_no")["Lat"].mean().reset_index()
reporting_area_centers_clusters=pd.merge(reporting_area_centers_clusters,reporting_area_centers.groupby("cluster_no")["Long"].mean().reset_index(),left_on="cluster_no",right_on="cluster_no")
reporting_area_centers_clusters

cluster_no        Lat       Long
0             0  42.332979 -71.055322
1             1  42.263788 -71.120683
2             2  42.351111 -71.128802
3             3  42.328831 -71.087448
4             4  42.288759 -71.060760
..          ...        ...        ...
495         495  42.282260 -71.166248
496         496  42.328609 -71.054394
497         497  42.267100 -71.103610
498         498  42.347598 -71.068130
499         499  42.354977 -71.148648

[500 rows x 3 columns]

In [9]:
import geopandas as gpd
from shapely import wkt

In [10]:
geodf_ra = gpd.GeoDataFrame(reporting_area_centers,geometry=reporting_area_centers["geom"].apply(wkt.loads))
geodf_ra

REPORTING_AREA       Long        Lat  \
0                  -71.079019  42.328928   
1                1 -70.996655  42.390179   
2               10 -71.008469  42.388751   
3              100 -71.054884  42.357810   
4              101 -71.054358  42.357237   
..             ...        ...        ...   
874            961 -71.125507  42.256711   
875            962 -71.072722  42.341868   
876             97 -71.058791  42.358096   
877             98 -71.057834  42.357567   
878             99 -71.056122  42.357940   

                                             geom  cluster_no  \
0     POINT(-71.07901926097279 42.32892816517891)          54   
1     POINT(-70.99665524078951 42.39017944236842)         202   
2     POINT(-71.00846862046863 42.38875119562499)         393   
3     POINT(-71.05488435035824 42.35781029024798)         311   
4    POINT(-71.05435766527813 42.357236672872574)         311   
..                                            ...         ...   
874   POINT(-71.12550696916665 42.25671135083332)         258   
875  POINT(-71.07272215000009 42.341867650000026)         396   
876   POINT(-71.05879099596038 42.35809580782488)         120   
877  POINT(-71.05783420354408 42.357566826483406)         390   
878  POINT(-71.05612151029125 42.357940040582555)         311   

                       geometry  
0    POINT (-71.07902 42.32893)  
1    POINT (-70.99666 42.39018)  
2    POINT (-71.00847 42.38875)  
3    POINT (-71.05488 42.35781)  
4    POINT (-71.05436 42.35724)  
..                          ...  
874  POINT (-71.12551 42.25671)  
875  POINT (-71.07272 42.34187)  
876  POINT (-71.05879 42.35810)  
877  POINT (-71.05783 42.35757)  
878  POINT (-71.05612 42.35794)  

[879 rows x 6 columns]

In [11]:
geodf_ra['cluster_no'].nunique()

500

In [12]:
df = df.merge(geodf_ra, on='REPORTING_AREA', how='inner')
df

INCIDENT_NUMBER  OFFENSE_CODE               OFFENSE_CODE_GROUP  \
0           I182080058          2403               Disorderly Conduct   
1           I182079552          2629                       Harassment   
2           I182079055          3831  Motor Vehicle Accident Response   
3           I182078637          3115               Investigate Person   
4           I182077199          3831  Motor Vehicle Accident Response   
...                ...           ...                              ...   
306408      I152073866          3106          Property Related Damage   
306409      I152072178          3006               Medical Assistance   
306410      I152054904          2629                       Harassment   
306411      I152050553          3802  Motor Vehicle Accident Response   
306412      I152057556          3301                  Verbal Disputes   

                          OFFENSE_DESCRIPTION DISTRICT REPORTING_AREA  \
0                        DISTURBING THE PEACE      E18            495   
1                                  HARASSMENT      E18            495   
2       M/V - LEAVING SCENE - PROPERTY DAMAGE      E18            495   
3                          INVESTIGATE PERSON      E18            495   
4       M/V - LEAVING SCENE - PROPERTY DAMAGE      E18            495   
...                                       ...      ...            ...   
306408           PROPERTY - ACCIDENTAL DAMAGE       E5            659   
306409          SICK/INJURED/MEDICAL - PERSON       E5            659   
306410                             HARASSMENT       E5            659   
306411        M/V ACCIDENT - PROPERTY  DAMAGE       E5            659   
306412                         VERBAL DISPUTE       B3            950   

       SHOOTING     OCCURRED_ON_DATE  YEAR  MONTH  ...    UCR_PART  \
0           NaN  2018-10-03 20:13:00  2018     10  ...    Part Two   
1           NaN  2018-10-02 10:22:02  2018     10  ...    Part Two   
2           NaN  2018-09-30 12:00:00  2018      9  ...  Part Three   
3           NaN  2018-09-28 23:11:00  2018      9  ...  Part Three   
4           NaN  2018-09-24 10:30:00  2018      9  ...  Part Three   
...         ...                  ...   ...    ...  ...         ...   
306408      NaN  2015-09-05 18:11:00  2015      9  ...  Part Three   
306409      NaN  2015-08-31 05:09:00  2015      8  ...  Part Three   
306410      NaN  2015-07-03 00:00:00  2015      7  ...    Part Two   
306411      NaN  2015-06-18 15:13:00  2015      6  ...  Part Three   
306412      NaN  2015-07-12 14:57:00  2015      7  ...  Part Three   

               STREET      Lat_x     Long_x                     Location  \
0        ARLINGTON ST  42.262608 -71.121186  (42.26260773, -71.12118637)   
1       GREENWOOD AVE  42.265460 -71.120239  (42.26546031, -71.12023924)   
2        ARLINGTON ST  42.262743 -71.121607  (42.26274326, -71.12160671)   
3        ARLINGTON ST  42.263040 -71.122303  (42.26303952, -71.12230282)   
4       HYDE PARK AVE  42.262169 -71.121856  (42.26216909, -71.12185558)   
...               ...        ...        ...                          ...   
306408     GRETTER RD  42.294650 -71.142209  (42.29465032, -71.14220871)   
306409     GRETTER RD  42.294650 -71.142209  (42.29465032, -71.14220871)   
306410     GRETTER RD  42.294650 -71.142209  (42.29465032, -71.14220871)   
306411        WELD ST  42.293356 -71.141822  (42.29335577, -71.14182237)   
306412       EVANS ST  42.282293 -71.080889  (42.28229312, -71.08088944)   

           Long_y      Lat_y                                          geom  \
0      -71.120683  42.263788   POINT(-71.12068302034626 42.26378807967414)   
1      -71.120683  42.263788   POINT(-71.12068302034626 42.26378807967414)   
2      -71.120683  42.263788   POINT(-71.12068302034626 42.26378807967414)   
3      -71.120683  42.263788   POINT(-71.12068302034626 42.26378807967414)   
4      -71.120683  42.263788   POINT(-71.12068302034626 42.26378807967414)   
...           ...        ...   

In [13]:
df['DAY_OF_WEEK'] = df['DAY_OF_WEEK'].map({
    'Tuesday':4, 
    'Saturday':2, 
    'Monday':3, 
    'Sunday':1, 
    'Thursday':5, 
    'Wednesday':6,
    'Friday':7
})
df

INCIDENT_NUMBER  OFFENSE_CODE               OFFENSE_CODE_GROUP  \
0           I182080058          2403               Disorderly Conduct   
1           I182079552          2629                       Harassment   
2           I182079055          3831  Motor Vehicle Accident Response   
3           I182078637          3115               Investigate Person   
4           I182077199          3831  Motor Vehicle Accident Response   
...                ...           ...                              ...   
306408      I152073866          3106          Property Related Damage   
306409      I152072178          3006               Medical Assistance   
306410      I152054904          2629                       Harassment   
306411      I152050553          3802  Motor Vehicle Accident Response   
306412      I152057556          3301                  Verbal Disputes   

                          OFFENSE_DESCRIPTION DISTRICT REPORTING_AREA  \
0                        DISTURBING THE PEACE      E18            495   
1                                  HARASSMENT      E18            495   
2       M/V - LEAVING SCENE - PROPERTY DAMAGE      E18            495   
3                          INVESTIGATE PERSON      E18            495   
4       M/V - LEAVING SCENE - PROPERTY DAMAGE      E18            495   
...                                       ...      ...            ...   
306408           PROPERTY - ACCIDENTAL DAMAGE       E5            659   
306409          SICK/INJURED/MEDICAL - PERSON       E5            659   
306410                             HARASSMENT       E5            659   
306411        M/V ACCIDENT - PROPERTY  DAMAGE       E5            659   
306412                         VERBAL DISPUTE       B3            950   

       SHOOTING     OCCURRED_ON_DATE  YEAR  MONTH  ...    UCR_PART  \
0           NaN  2018-10-03 20:13:00  2018     10  ...    Part Two   
1           NaN  2018-10-02 10:22:02  2018     10  ...    Part Two   
2           NaN  2018-09-30 12:00:00  2018      9  ...  Part Three   
3           NaN  2018-09-28 23:11:00  2018      9  ...  Part Three   
4           NaN  2018-09-24 10:30:00  2018      9  ...  Part Three   
...         ...                  ...   ...    ...  ...         ...   
306408      NaN  2015-09-05 18:11:00  2015      9  ...  Part Three   
306409      NaN  2015-08-31 05:09:00  2015      8  ...  Part Three   
306410      NaN  2015-07-03 00:00:00  2015      7  ...    Part Two   
306411      NaN  2015-06-18 15:13:00  2015      6  ...  Part Three   
306412      NaN  2015-07-12 14:57:00  2015      7  ...  Part Three   

               STREET      Lat_x     Long_x                     Location  \
0        ARLINGTON ST  42.262608 -71.121186  (42.26260773, -71.12118637)   
1       GREENWOOD AVE  42.265460 -71.120239  (42.26546031, -71.12023924)   
2        ARLINGTON ST  42.262743 -71.121607  (42.26274326, -71.12160671)   
3        ARLINGTON ST  42.263040 -71.122303  (42.26303952, -71.12230282)   
4       HYDE PARK AVE  42.262169 -71.121856  (42.26216909, -71.12185558)   
...               ...        ...        ...                          ...   
306408     GRETTER RD  42.294650 -71.142209  (42.29465032, -71.14220871)   
306409     GRETTER RD  42.294650 -71.142209  (42.29465032, -71.14220871)   
306410     GRETTER RD  42.294650 -71.142209  (42.29465032, -71.14220871)   
306411        WELD ST  42.293356 -71.141822  (42.29335577, -71.14182237)   
306412       EVANS ST  42.282293 -71.080889  (42.28229312, -71.08088944)   

           Long_y      Lat_y                                          geom  \
0      -71.120683  42.263788   POINT(-71.12068302034626 42.26378807967414)   
1      -71.120683  42.263788   POINT(-71.12068302034626 42.26378807967414)   
2      -71.120683  42.263788   POINT(-71.12068302034626 42.26378807967414)   
3      -71.120683  42.263788   POINT(-71.12068302034626 42.26378807967414)   
4      -71.120683  42.263788   POINT(-71.12068302034626 42.26378807967414)   
...           ...        ...   

In [14]:
df['Summer']=0
df['Summer']=df["MONTH"].apply(lambda x: 1 if x==6 or x==7 or x==8 or x==9 else 0)


df['HOUR_12_16_17_18']=0
df['HOUR_12_16_17_18']=df["HOUR"].apply(lambda x: 1 if x==12 or x==16 or x==17 or x==18 or x==19 else 0)
df


INCIDENT_NUMBER  OFFENSE_CODE               OFFENSE_CODE_GROUP  \
0           I182080058          2403               Disorderly Conduct   
1           I182079552          2629                       Harassment   
2           I182079055          3831  Motor Vehicle Accident Response   
3           I182078637          3115               Investigate Person   
4           I182077199          3831  Motor Vehicle Accident Response   
...                ...           ...                              ...   
306408      I152073866          3106          Property Related Damage   
306409      I152072178          3006               Medical Assistance   
306410      I152054904          2629                       Harassment   
306411      I152050553          3802  Motor Vehicle Accident Response   
306412      I152057556          3301                  Verbal Disputes   

                          OFFENSE_DESCRIPTION DISTRICT REPORTING_AREA  \
0                        DISTURBING THE PEACE      E18            495   
1                                  HARASSMENT      E18            495   
2       M/V - LEAVING SCENE - PROPERTY DAMAGE      E18            495   
3                          INVESTIGATE PERSON      E18            495   
4       M/V - LEAVING SCENE - PROPERTY DAMAGE      E18            495   
...                                       ...      ...            ...   
306408           PROPERTY - ACCIDENTAL DAMAGE       E5            659   
306409          SICK/INJURED/MEDICAL - PERSON       E5            659   
306410                             HARASSMENT       E5            659   
306411        M/V ACCIDENT - PROPERTY  DAMAGE       E5            659   
306412                         VERBAL DISPUTE       B3            950   

       SHOOTING     OCCURRED_ON_DATE  YEAR  MONTH  ...      Lat_x     Long_x  \
0           NaN  2018-10-03 20:13:00  2018     10  ...  42.262608 -71.121186   
1           NaN  2018-10-02 10:22:02  2018     10  ...  42.265460 -71.120239   
2           NaN  2018-09-30 12:00:00  2018      9  ...  42.262743 -71.121607   
3           NaN  2018-09-28 23:11:00  2018      9  ...  42.263040 -71.122303   
4           NaN  2018-09-24 10:30:00  2018      9  ...  42.262169 -71.121856   
...         ...                  ...   ...    ...  ...        ...        ...   
306408      NaN  2015-09-05 18:11:00  2015      9  ...  42.294650 -71.142209   
306409      NaN  2015-08-31 05:09:00  2015      8  ...  42.294650 -71.142209   
306410      NaN  2015-07-03 00:00:00  2015      7  ...  42.294650 -71.142209   
306411      NaN  2015-06-18 15:13:00  2015      6  ...  42.293356 -71.141822   
306412      NaN  2015-07-12 14:57:00  2015      7  ...  42.282293 -71.080889   

                           Location     Long_y      Lat_y  \
0       (42.26260773, -71.12118637) -71.120683  42.263788   
1       (42.26546031, -71.12023924) -71.120683  42.263788   
2       (42.26274326, -71.12160671) -71.120683  42.263788   
3       (42.26303952, -71.12230282) -71.120683  42.263788   
4       (42.26216909, -71.12185558) -71.120683  42.263788   
...                             ...        ...        ...   
306408  (42.29465032, -71.14220871) -71.142274  42.294403   
306409  (42.29465032, -71.14220871) -71.142274  42.294403   
306410  (42.29465032, -71.14220871) -71.142274  42.294403   
306411  (42.29335577, -71.14182237) -71.142274  42.294403   
306412  (42.28229312, -71.08088944) -71.080889  42.282293   

                                                geom cluster_no  \
0        POINT(-71.12068302034626 42.26378807967414)          1   
1        POINT(-71.12068302034626 42.26378807967414)          1   
2        POINT(-71.12068302034626 42.26378807967414)          1   
3        POINT(-71.12068302034626 42.26378807967414)          1   
4        POINT(-71.12068302034626 42.26378807967414)          1   
...                                              ...        ...   
306408  POINT(-71.14227353777778 42.294403277777775)        280   
306409  POINT(-71.14227

In [15]:
# df['DISTRICT'] = df['DISTRICT'].map({
#     'B3':1, 
#     'E18':2, 
#     'B2':3, 
#     'E5':4, 
#     'C6':5, 
#     'D14':6, 
#     'E13':7, 
#     'C11':8, 
#     'D4':9, 
#     'A7':10, 
#     'A1':11, 
#     'A15':12
# })

# df

In [16]:
def get_dummies(dataframe):
    
    #for DISTRICT column
    
    DISTRICT = pd.get_dummies(dataframe.DISTRICT, prefix = 'DIS')
    dataframe = pd.concat([dataframe,DISTRICT],axis = 1)
    dataframe = dataframe.drop(['DISTRICT'],axis = 1)
    
    #for UCR PART column
    
    UCR_PART = pd.get_dummies(dataframe.UCR_PART, prefix = 'UCR')
    dataframe = pd.concat([dataframe,UCR_PART],axis = 1)
    dataframe = dataframe.drop(['UCR_PART'],axis = 1)
    
    return dataframe
df =get_dummies(df)
df

INCIDENT_NUMBER  OFFENSE_CODE               OFFENSE_CODE_GROUP  \
0           I182080058          2403               Disorderly Conduct   
1           I182079552          2629                       Harassment   
2           I182079055          3831  Motor Vehicle Accident Response   
3           I182078637          3115               Investigate Person   
4           I182077199          3831  Motor Vehicle Accident Response   
...                ...           ...                              ...   
306408      I152073866          3106          Property Related Damage   
306409      I152072178          3006               Medical Assistance   
306410      I152054904          2629                       Harassment   
306411      I152050553          3802  Motor Vehicle Accident Response   
306412      I152057556          3301                  Verbal Disputes   

                          OFFENSE_DESCRIPTION REPORTING_AREA SHOOTING  \
0                        DISTURBING THE PEACE            495      NaN   
1                                  HARASSMENT            495      NaN   
2       M/V - LEAVING SCENE - PROPERTY DAMAGE            495      NaN   
3                          INVESTIGATE PERSON            495      NaN   
4       M/V - LEAVING SCENE - PROPERTY DAMAGE            495      NaN   
...                                       ...            ...      ...   
306408           PROPERTY - ACCIDENTAL DAMAGE            659      NaN   
306409          SICK/INJURED/MEDICAL - PERSON            659      NaN   
306410                             HARASSMENT            659      NaN   
306411        M/V ACCIDENT - PROPERTY  DAMAGE            659      NaN   
306412                         VERBAL DISPUTE            950      NaN   

           OCCURRED_ON_DATE  YEAR  MONTH  DAY_OF_WEEK  ...  DIS_C6 DIS_D14  \
0       2018-10-03 20:13:00  2018     10            6  ...       0       0   
1       2018-10-02 10:22:02  2018     10            4  ...       0       0   
2       2018-09-30 12:00:00  2018      9            1  ...       0       0   
3       2018-09-28 23:11:00  2018      9            7  ...       0       0   
4       2018-09-24 10:30:00  2018      9            3  ...       0       0   
...                     ...   ...    ...          ...  ...     ...     ...   
306408  2015-09-05 18:11:00  2015      9            2  ...       0       0   
306409  2015-08-31 05:09:00  2015      8            3  ...       0       0   
306410  2015-07-03 00:00:00  2015      7            7  ...       0       0   
306411  2015-06-18 15:13:00  2015      6            5  ...       0       0   
306412  2015-07-12 14:57:00  2015      7            1  ...       0       0   

        DIS_D4  DIS_E13 DIS_E18  DIS_E5  UCR_Other UCR_Part One  \
0            0        0       1       0          0            0   
1            0        0       1       0          0            0   
2            0        0       1       0          0            0   
3            0        0       1       0          0            0   
4            0        0       1       0          0            0   
...        ...      ...     ...     ...        ...          ...   
306408       0        0       0       1          0            0   
306409       0        0       0       1          0            0   
306410       0        0       0       1          0            0   
306411       0        0       0       1          0            0   
306412       0        0       0       0          0            0   

        UCR_Part Three UCR_Part Two  
0                    0            1  
1                    0            1  
2                    1            0  
3                    1            0  
4                    1            0  
...                ...          ...  
306408               1            0  
306409               1            0  
306410               0            1  
306411               1            0  
306412               1            0  

[306413 rows x 38 columns]

In [17]:
df.columns

Index(['INCIDENT_NUMBER', 'OFFENSE_CODE', 'OFFENSE_CODE_GROUP',
       'OFFENSE_DESCRIPTION', 'REPORTING_AREA', 'SHOOTING', 'OCCURRED_ON_DATE',
       'YEAR', 'MONTH', 'DAY_OF_WEEK', 'HOUR', 'STREET', 'Lat_x', 'Long_x',
       'Location', 'Long_y', 'Lat_y', 'geom', 'cluster_no', 'geometry',
       'Summer', 'HOUR_12_16_17_18', 'DIS_A1', 'DIS_A15', 'DIS_A7', 'DIS_B2',
       'DIS_B3', 'DIS_C11', 'DIS_C6', 'DIS_D14', 'DIS_D4', 'DIS_E13',
       'DIS_E18', 'DIS_E5', 'UCR_Other', 'UCR_Part One', 'UCR_Part Three',
       'UCR_Part Two'],
      dtype='object')

In [18]:
important_crimes= ['Aggravated Assault', 
      'Harassment', 
       'Arson', 
       'Homicide', 
       'Criminal Harassment', 
       'Biological Threat',
       'Manslaughter', 'HUMAN TRAFFICKING',
        'Auto Theft', 'Larceny','Robbery','Residential Burglary','Larcency From Motor Vehicle','Other Burglary','Commercial Burglary']

In [19]:
df['important']=0
i=0
for x in df['OFFENSE_CODE_GROUP']:
      if x in important_crimes:
        df['important'].iloc[i]=1
    
      i+=1
df

/opt/conda/lib/python3.7/site-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)


INCIDENT_NUMBER  OFFENSE_CODE               OFFENSE_CODE_GROUP  \
0           I182080058          2403               Disorderly Conduct   
1           I182079552          2629                       Harassment   
2           I182079055          3831  Motor Vehicle Accident Response   
3           I182078637          3115               Investigate Person   
4           I182077199          3831  Motor Vehicle Accident Response   
...                ...           ...                              ...   
306408      I152073866          3106          Property Related Damage   
306409      I152072178          3006               Medical Assistance   
306410      I152054904          2629                       Harassment   
306411      I152050553          3802  Motor Vehicle Accident Response   
306412      I152057556          3301                  Verbal Disputes   

                          OFFENSE_DESCRIPTION REPORTING_AREA SHOOTING  \
0                        DISTURBING THE PEACE            495      NaN   
1                                  HARASSMENT            495      NaN   
2       M/V - LEAVING SCENE - PROPERTY DAMAGE            495      NaN   
3                          INVESTIGATE PERSON            495      NaN   
4       M/V - LEAVING SCENE - PROPERTY DAMAGE            495      NaN   
...                                       ...            ...      ...   
306408           PROPERTY - ACCIDENTAL DAMAGE            659      NaN   
306409          SICK/INJURED/MEDICAL - PERSON            659      NaN   
306410                             HARASSMENT            659      NaN   
306411        M/V ACCIDENT - PROPERTY  DAMAGE            659      NaN   
306412                         VERBAL DISPUTE            950      NaN   

           OCCURRED_ON_DATE  YEAR  MONTH  DAY_OF_WEEK  ...  DIS_D14 DIS_D4  \
0       2018-10-03 20:13:00  2018     10            6  ...        0      0   
1       2018-10-02 10:22:02  2018     10            4  ...        0      0   
2       2018-09-30 12:00:00  2018      9            1  ...        0      0   
3       2018-09-28 23:11:00  2018      9            7  ...        0      0   
4       2018-09-24 10:30:00  2018      9            3  ...        0      0   
...                     ...   ...    ...          ...  ...      ...    ...   
306408  2015-09-05 18:11:00  2015      9            2  ...        0      0   
306409  2015-08-31 05:09:00  2015      8            3  ...        0      0   
306410  2015-07-03 00:00:00  2015      7            7  ...        0      0   
306411  2015-06-18 15:13:00  2015      6            5  ...        0      0   
306412  2015-07-12 14:57:00  2015      7            1  ...        0      0   

        DIS_E13  DIS_E18 DIS_E5  UCR_Other  UCR_Part One UCR_Part Three  \
0             0        1      0          0             0              0   
1             0        1      0          0             0              0   
2             0        1      0          0             0              1   
3             0        1      0          0             0              1   
4             0        1      0          0             0              1   
...         ...      ...    ...        ...           ...            ...   
306408        0        0      1          0             0              1   
306409        0        0      1          0             0              1   
306410        0        0      1          0             0              0   
306411        0        0      1          0             0              1   
306412        0        0      0          0             0              1   

        UCR_Part Two important  
0                  1         0  
1                  1         1  
2                  0         0  
3                  0         0  
4                  0         0  
...              ...       ...  
306408             0         0  
306409             0         0  
306410             1         1  
306411             0         0  
306412             0         0  

[306413 rows x 39 

In [20]:
df["OCCURRED_ON_DATE"]=pd.to_datetime(df["OCCURRED_ON_DATE"],infer_datetime_format=True)
df["OCCURRED_DAY"]=df["OCCURRED_ON_DATE"].apply(lambda x: x.date())
df = df.drop(['OCCURRED_ON_DATE'],axis = 1)
df

INCIDENT_NUMBER  OFFENSE_CODE               OFFENSE_CODE_GROUP  \
0           I182080058          2403               Disorderly Conduct   
1           I182079552          2629                       Harassment   
2           I182079055          3831  Motor Vehicle Accident Response   
3           I182078637          3115               Investigate Person   
4           I182077199          3831  Motor Vehicle Accident Response   
...                ...           ...                              ...   
306408      I152073866          3106          Property Related Damage   
306409      I152072178          3006               Medical Assistance   
306410      I152054904          2629                       Harassment   
306411      I152050553          3802  Motor Vehicle Accident Response   
306412      I152057556          3301                  Verbal Disputes   

                          OFFENSE_DESCRIPTION REPORTING_AREA SHOOTING  YEAR  \
0                        DISTURBING THE PEACE            495      NaN  2018   
1                                  HARASSMENT            495      NaN  2018   
2       M/V - LEAVING SCENE - PROPERTY DAMAGE            495      NaN  2018   
3                          INVESTIGATE PERSON            495      NaN  2018   
4       M/V - LEAVING SCENE - PROPERTY DAMAGE            495      NaN  2018   
...                                       ...            ...      ...   ...   
306408           PROPERTY - ACCIDENTAL DAMAGE            659      NaN  2015   
306409          SICK/INJURED/MEDICAL - PERSON            659      NaN  2015   
306410                             HARASSMENT            659      NaN  2015   
306411        M/V ACCIDENT - PROPERTY  DAMAGE            659      NaN  2015   
306412                         VERBAL DISPUTE            950      NaN  2015   

        MONTH  DAY_OF_WEEK  HOUR  ... DIS_D4  DIS_E13  DIS_E18 DIS_E5  \
0          10            6    20  ...      0        0        1      0   
1          10            4    10  ...      0        0        1      0   
2           9            1    12  ...      0        0        1      0   
3           9            7    23  ...      0        0        1      0   
4           9            3    10  ...      0        0        1      0   
...       ...          ...   ...  ...    ...      ...      ...    ...   
306408      9            2    18  ...      0        0        0      1   
306409      8            3     5  ...      0        0        0      1   
306410      7            7     0  ...      0        0        0      1   
306411      6            5    15  ...      0        0        0      1   
306412      7            1    14  ...      0        0        0      0   

        UCR_Other  UCR_Part One UCR_Part Three  UCR_Part Two important  \
0               0             0              0             1         0   
1               0             0              0             1         1   
2               0             0              1             0         0   
3               0             0              1             0         0   
4               0             0              1             0         0   
...           ...           ...            ...           ...       ...   
306408          0             0              1             0         0   
306409          0             0              1             0         0   
306410          0             0              0             1         1   
306411          0             0              1             0         0   
306412          0             0              1             0         0   

        OCCURRED_DAY  
0         2018-10-03  
1         2018-10-02  
2         2018-09-30  
3         2018-09-28  
4         2018-09-24  
...              ...  
306408    2015-09-05  
306409    2015-08-31  
306410    2015-07-03  
306411    2015-06-18  
306412    2015-07-12  

[306413 rows x 39 columns]

In [21]:
df = df.sort_values(by =['OCCURRED_DAY'], ascending=False)
df['OCCURRED_DAY']= pd.to_datetime(df['OCCURRED_DAY'])
df

INCIDENT_NUMBER  OFFENSE_CODE          OFFENSE_CODE_GROUP  \
0           I182080058          2403          Disorderly Conduct   
69364       I182079874          3301             Verbal Disputes   
53696       I182079846          1503          Firearm Violations   
53697       I182079846          1841              Drug Violation   
76221       I182079857          2405          Disorderly Conduct   
...                ...           ...                         ...   
221347      I152049585          2906                  Violations   
27852       I152049595          2670         Criminal Harassment   
71621       I152049580          3006          Medical Assistance   
27851       I152049998           615  Larceny From Motor Vehicle   
85919       I152049743          3006          Medical Assistance   

                                   OFFENSE_DESCRIPTION REPORTING_AREA  \
0                                 DISTURBING THE PEACE            495   
69364                                   VERBAL DISPUTE            235   
53696      WEAPON - OTHER - CARRYING / POSSESSING, ETC            916   
53697   DRUGS - POSS CLASS A - INTENT TO MFR DIST DISP            916   
76221                               DISORDERLY CONDUCT            958   
...                                                ...            ...   
221347                VAL - OPERATING UNREG/UNINS  CAR             69   
27852                              CRIMINAL HARASSMENT            915   
71621                    SICK/INJURED/MEDICAL - PERSON            282   
27851          LARCENY THEFT OF MV PARTS & ACCESSORIES            915   
85919                    SICK/INJURED/MEDICAL - PERSON            186   

       SHOOTING  YEAR  MONTH  DAY_OF_WEEK  HOUR  ... DIS_D4  DIS_E13  DIS_E18  \
0           NaN  2018     10            6    20  ...      0        0        1   
69364       NaN  2018     10            6    11  ...      0        0        0   
53696       NaN  2018     10            6    10  ...      0        1        0   
53697       NaN  2018     10            6    10  ...      0        1        0   
76221       NaN  2018     10            6    10  ...      0        0        0   
...         ...   ...    ...          ...   ...  ...    ...      ...      ...   
221347      NaN  2015      6            3     1  ...      0        0        0   
27852       NaN  2015      6            3     1  ...      0        0        0   
71621       NaN  2015      6            3    12  ...      0        0        0   
27851       NaN  2015      6            3    21  ...      0        0        0   
85919       NaN  2015      6            3    20  ...      0        0        0   

       DIS_E5  UCR_Other  UCR_Part One UCR_Part Three  UCR_Part Two important  \
0           0          0             0              0             1         0   
69364       0          0             0              1             0         0   
53696       0          0             0              0             1         0   
53697       0          0             0              0             1         0   
76221       0          0             0              0             1         0   
...       ...        ...           ...            ...           ...       ...   
221347      0          0             0              0             1         0   
27852       0          0             0              0             1         1   
71621       0          0             0              1             0         0   
27851       0          0             1              0             0         0   
85919       0          0             0              1             0         0   

        OCCURRED_DAY  
0         2018-10-03  
69364     2018-10-03  
53696     2018-10-03  
53697     2018-10-03  
76221     2018-10-03  
...              ...  
221347    2015-06-15  
27852     2015-06-15  
71621     2015-06-15  
27851     2015-06-15  
85919     2015-06-15  

[306413 rows x 39 columns]

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 306413 entries, 0 to 85919
Data columns (total 39 columns):
 #   Column               Non-Null Count   Dtype         
---  ------               --------------   -----         
 0   INCIDENT_NUMBER      306413 non-null  object        
 1   OFFENSE_CODE         306413 non-null  int64         
 2   OFFENSE_CODE_GROUP   306413 non-null  object        
 3   OFFENSE_DESCRIPTION  306413 non-null  object        
 4   REPORTING_AREA       306413 non-null  object        
 5   SHOOTING             1018 non-null    object        
 6   YEAR                 306413 non-null  int64         
 7   MONTH                306413 non-null  int64         
 8   DAY_OF_WEEK          306413 non-null  int64         
 9   HOUR                 306413 non-null  int64         
 10  STREET               304631 non-null  object        
 11  Lat_x                306413 non-null  float64       
 12  Long_x               306413 non-null  float64       
 13  Location       

In [23]:
from sklearn.utils import shuffle
df = shuffle(df)

In [24]:
train_set = df[['Lat_y','Long_y','cluster_no','MONTH','HOUR','DIS_A1','DIS_A15','DIS_A7','DIS_B2','DIS_B3', 'DIS_C11', 'DIS_C6', 'DIS_D14', 'DIS_D4', 'DIS_E13', 'DIS_E18', 'DIS_E5','important']].head((int(len(df) *0.8)))
train_set

Lat_y     Long_y  cluster_no  MONTH  HOUR  DIS_A1  DIS_A15  \
305031  42.290586 -71.047062          26     12    15       0        0   
104309  42.350515 -71.056398         351      8    22       1        0   
125226  42.288121 -71.088172         143     11     2       0        0   
77437   42.338450 -71.054102         177      7    23       0        0   
289988  42.345373 -71.085509         164      9    18       0        0   
...           ...        ...         ...    ...   ...     ...      ...   
80966   42.317545 -71.065222          72      8    12       0        0   
280547  42.358752 -71.051465         361      7    16       1        0   
103518  42.342002 -71.089599         200      6    10       0        0   
125302  42.323820 -71.098240         180      5    15       0        0   
37067   42.331327 -71.098467          40      1     0       0        0   

        DIS_A7  DIS_B2  DIS_B3  DIS_C11  DIS_C6  DIS_D14  DIS_D4  DIS_E13  \
305031       0       0       0        1       0        0       0        0   
104309       0       0       0        0       0        0       0        0   
125226       0       0       1        0       0        0       0        0   
77437        0       0       0        0       1        0       0        0   
289988       0       0       0        0       0        0       1        0   
...        ...     ...     ...      ...     ...      ...     ...      ...   
80966        0       1       0        0       0        0       0        0   
280547       0       0       0        0       0        0       0        0   
103518       0       0       0        0       0        0       1        0   
125302       0       0       0        0       0        0       0        1   
37067        0       1       0        0       0        0       0        0   

        DIS_E18  DIS_E5  important  
305031        0       0          0  
104309        0       0          0  
125226        0       0          0  
77437         0       0          0  
289988        0       0          1  
...         ...     ...        ...  
80966         0       0          0  
280547        0       0          0  
103518        0       0          1  
125302        0       0          0  
37067         0       0          0  

[245130 rows x 18 columns]

In [25]:
validation_set = df.tail(int(len(df) *0.2))[['Lat_y','Long_y','cluster_no','MONTH','HOUR','DIS_A1','DIS_A15','DIS_A7','DIS_B2','DIS_B3', 'DIS_C11', 'DIS_C6', 'DIS_D14', 'DIS_D4', 'DIS_E13', 'DIS_E18', 'DIS_E5','important']]
validation_set


Lat_y     Long_y  cluster_no  MONTH  HOUR  DIS_A1  DIS_A15  \
116759  42.353895 -71.061395         386     12     7       1        0   
38261   42.354049 -71.062869         386      8    15       1        0   
3050    42.308620 -71.079876         371      7     1       0        0   
31609   42.345931 -71.096667         420      6    20       0        0   
15591   42.314352 -71.106933         456      9    14       0        0   
...           ...        ...         ...    ...   ...     ...      ...   
34120   42.288459 -71.065189         213      2    17       0        0   
24396   42.328736 -71.077378          54      4    15       0        0   
215878  42.334812 -71.073720         195      7     0       0        0   
37376   42.333045 -71.036517         319     10    21       0        0   
93476   42.350595 -71.133939         172      8     4       0        0   

        DIS_A7  DIS_B2  DIS_B3  DIS_C11  DIS_C6  DIS_D14  DIS_D4  DIS_E13  \
116759       0       0       0        0       0        0       0        0   
38261        0       0       0        0       0        0       0        0   
3050         0       1       0        0       0        0       0        0   
31609        0       0       0        0       0        0       1        0   
15591        0       0       0        0       0        0       0        1   
...        ...     ...     ...      ...     ...      ...     ...      ...   
34120        0       0       0        1       0        0       0        0   
24396        0       1       0        0       0        0       0        0   
215878       0       0       0        0       0        0       1        0   
37376        0       0       0        0       1        0       0        0   
93476        0       0       0        0       0        1       0        0   

        DIS_E18  DIS_E5  important  
116759        0       0          0  
38261         0       0          0  
3050          0       0          0  
31609         0       0          0  
15591         0       0          1  
...         ...     ...        ...  
34120         0       0          0  
24396         0       0          0  
215878        0       0          1  
37376         0       0          0  
93476         0       0          0  

[61282 rows x 18 columns]

In [26]:
groundTruth= validation_set['important'].to_frame()

groundTruth

important
116759          0
38261           0
3050            0
31609           0
15591           1
...           ...
34120           0
24396           0
215878          1
37376           0
93476           0

[61282 rows x 1 columns]

In [27]:
from sklearn.preprocessing import StandardScaler

In [28]:
scaler = StandardScaler()
train_scaled = scaler.fit_transform(train_set)
train_scaled = pd.DataFrame(data=train_scaled, columns=['Lat_y','Long_y','cluster_no','MONTH','HOUR','DIS_A1','DIS_A15','DIS_A7','DIS_B2','DIS_B3', 'DIS_C11', 'DIS_C6', 'DIS_D14', 'DIS_D4', 'DIS_E13', 'DIS_E18', 'DIS_E5', 'important'])

train_scaled

Lat_y    Long_y  cluster_no     MONTH      HOUR    DIS_A1  \
0      -1.008495  1.217260   -1.538574  1.634396  0.298956 -0.347178   
1       0.894574  0.899466    0.754336  0.406370  1.415148  2.880364   
2      -1.086774 -0.182137   -0.713126  1.327390 -1.773971 -0.347178   
3       0.511438  0.977640   -0.473253  0.099364  1.574604 -0.347178   
4       0.731306 -0.091462   -0.564969  0.713377  0.777324 -0.347178   
...          ...       ...         ...       ...       ...       ...   
245125 -0.152388  0.599099   -1.214039  0.406370 -0.179412 -0.347178   
245126  1.156158  1.067391    0.824887  0.099364  0.458412  2.880364   
245127  0.624233 -0.230685   -0.310985 -0.207643 -0.498324 -0.347178   
245128  0.046880 -0.524844   -0.452087 -0.514650  0.298956 -0.347178   
245129  0.285265 -0.532558   -1.439802 -1.742676 -2.092883 -0.347178   

         DIS_A15    DIS_A7    DIS_B2    DIS_B3   DIS_C11    DIS_C6   DIS_D14  \
0      -0.144652 -0.211924 -0.429169 -0.356397  2.513427 -0.281648 -0.261174   
1      -0.144652 -0.211924 -0.429169 -0.356397 -0.397863 -0.281648 -0.261174   
2      -0.144652 -0.211924 -0.429169  2.805858 -0.397863 -0.281648 -0.261174   
3      -0.144652 -0.211924 -0.429169 -0.356397 -0.397863  3.550527 -0.261174   
4      -0.144652 -0.211924 -0.429169 -0.356397 -0.397863 -0.281648 -0.261174   
...          ...       ...       ...       ...       ...       ...       ...   
245125 -0.144652 -0.211924  2.330086 -0.356397 -0.397863 -0.281648 -0.261174   
245126 -0.144652 -0.211924 -0.429169 -0.356397 -0.397863 -0.281648 -0.261174   
245127 -0.144652 -0.211924 -0.429169 -0.356397 -0.397863 -0.281648 -0.261174   
245128 -0.144652 -0.211924 -0.429169 -0.356397 -0.397863 -0.281648 -0.261174   
245129 -0.144652 -0.211924  2.330086 -0.356397 -0.397863 -0.281648 -0.261174   

          DIS_D4   DIS_E13   DIS_E18    DIS_E5  important  
0      -0.386319 -0.242815 -0.243145 -0.210797  -0.463954  
1      -0.386319 -0.242815 -0.243145 -0.210797  -0.463954  
2      -0.386319 -0.242815 -0.243145 -0.210797  -0.463954  
3      -0.386319 -0.242815 -0.243145 -0.210797  -0.463954  
4       2.588532 -0.242815 -0.243145 -0.210797   2.155385  
...          ...       ...       ...       ...        ...  
245125 -0.386319 -0.242815 -0.243145 -0.210797  -0.463954  
245126 -0.386319 -0.242815 -0.243145 -0.210797  -0.463954  
245127  2.588532 -0.242815 -0.243145 -0.210797   2.155385  
245128 -0.386319  4.118358 -0.243145 -0.210797  -0.463954  
245129 -0.386319 -0.242815 -0.243145 -0.210797  -0.463954  

[245130 rows x 18 columns]

In [29]:
scaled_validation_set = scaler.fit_transform(validation_set)
scaled_validation_set = pd.DataFrame(data=scaled_validation_set, columns=['Lat_y','Long_y','cluster_no','MONTH','HOUR','DIS_A1','DIS_A15','DIS_A7','DIS_B2','DIS_B3', 'DIS_C11', 'DIS_C6', 'DIS_D14', 'DIS_D4', 'DIS_E13', 'DIS_E18', 'DIS_E5', 'important'])
scaled_validation_set = scaled_validation_set.drop('important', axis=1)
scaled_validation_set

Lat_y    Long_y  cluster_no     MONTH      HOUR    DIS_A1   DIS_A15  \
0      1.009785  0.731343    1.008872  1.633826 -0.970160  2.888212 -0.145356   
1      1.014682  0.681256    1.008872  0.408380  0.299475  2.888212 -0.145356   
2     -0.427400  0.103400    0.902832  0.102019 -1.922386 -0.346235 -0.145356   
3      0.756980 -0.467129    1.249230 -0.204343  1.092996 -0.346235 -0.145356   
4     -0.245472 -0.815913    1.503726  0.714742  0.140770 -0.346235 -0.145356   
...         ...       ...         ...       ...       ...       ...       ...   
61277 -1.067407  0.602431   -0.214124 -1.429788  0.616883 -0.346235 -0.145356   
61278  0.211139  0.188275   -1.338150 -0.817065  0.299475 -0.346235 -0.145356   
61279  0.404036  0.312578   -0.341372  0.102019 -2.081090 -0.346235 -0.145356   
61280  0.347932  1.576630    0.535226  1.021103  1.251701 -0.346235 -0.145356   
61281  0.905046 -1.733521   -0.503967  0.408380 -1.446273 -0.346235 -0.145356   

         DIS_A7    DIS_B2    DIS_B3   DIS_C11    DIS_C6   DIS_D14    DIS_D4  \
0     -0.208497 -0.424422 -0.358641 -0.404772 -0.281616 -0.262660 -0.383884   
1     -0.208497 -0.424422 -0.358641 -0.404772 -0.281616 -0.262660 -0.383884   
2     -0.208497  2.356146 -0.358641 -0.404772 -0.281616 -0.262660 -0.383884   
3     -0.208497 -0.424422 -0.358641 -0.404772 -0.281616 -0.262660  2.604956   
4     -0.208497 -0.424422 -0.358641 -0.404772 -0.281616 -0.262660 -0.383884   
...         ...       ...       ...       ...       ...       ...       ...   
61277 -0.208497 -0.424422 -0.358641  2.470529 -0.281616 -0.262660 -0.383884   
61278 -0.208497  2.356146 -0.358641 -0.404772 -0.281616 -0.262660 -0.383884   
61279 -0.208497 -0.424422 -0.358641 -0.404772 -0.281616 -0.262660  2.604956   
61280 -0.208497 -0.424422 -0.358641 -0.404772  3.550936 -0.262660 -0.383884   
61281 -0.208497 -0.424422 -0.358641 -0.404772 -0.281616  3.807206 -0.383884   

        DIS_E13   DIS_E18    DIS_E5  
0     -0.240964 -0.242779 -0.212512  
1     -0.240964 -0.242779 -0.212512  
2     -0.240964 -0.242779 -0.212512  
3     -0.240964 -0.242779 -0.212512  
4      4.149990 -0.242779 -0.212512  
...         ...       ...       ...  
61277 -0.240964 -0.242779 -0.212512  
61278 -0.240964 -0.242779 -0.212512  
61279 -0.240964 -0.242779 -0.212512  
61280 -0.240964 -0.242779 -0.212512  
61281 -0.240964 -0.242779 -0.212512  

[61282 rows x 17 columns]

In [30]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import BernoulliNB
from sklearn.tree import ExtraTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.semi_supervised import LabelSpreading
from sklearn.svm import LinearSVC
from sklearn.neighbors.nearest_centroid import NearestCentroid
from sklearn.ensemble import RandomForestClassifier
from lightgbm import LGBMClassifier

/opt/conda/lib/python3.7/site-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.neighbors.nearest_centroid module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)


In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

def classification_metrics(y_test, predict):
    print("Confusion Matrix:\n")
    print(confusion_matrix(y_test, predict))
    print("\nAccuracy: ", accuracy_score(y_test, predict))
    print("\nClassification report:\n")
    print(classification_report(y_test, predict))

In [32]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(train_scaled.drop(columns=["important"]), train_set["important"], random_state = 0, test_size = 0.33, shuffle=True)  

In [33]:
from xgboost import XGBClassifier

xgB = XGBClassifier(learning_rate =0.1, n_estimators=1000,
    max_depth=10, min_child_weight=5, subsample=0.8,colsample_bytree=0.8,
    objective= 'binary:logistic', scale_pos_weight = 6, random_state=0)
xgB.fit(x_train, y_train)
xgb_test_predict = pd.DataFrame(data=xgB.predict(x_test))
classification_metrics(y_test, xgb_test_predict)

Confusion Matrix:

[[41901 24665]
 [ 7119  7208]]

Accuracy:  0.6070859036010532

Classification report:

              precision    recall  f1-score   support

           0       0.85      0.63      0.73     66566
           1       0.23      0.50      0.31     14327

    accuracy                           0.61     80893
   macro avg       0.54      0.57      0.52     80893
weighted avg       0.74      0.61      0.65     80893



In [34]:
# Positive Prediction | Negative Prediction
# True Positive (TP)  | False Negative (FN)
# False Positive (FP) | True Negative (TN)


# Recall; False Negative olarak tahminlemenin maliyetinin yüksek olduğu durumlarda
# Precision;  False Positive tahminlemenin maliyeti yüksek olduğu durumlarda (0lara ne kadar 1 dediğim çok önemli değil, fakat 1lere ne kadar 0 dediğim önemli) 
# extra police force gerekbilir fakat suç önlenme anlamında riski azaltmak için 1 classındaki recall değerini artırdık

In [35]:
xgb_valid_predict = pd.DataFrame(data=xgB.predict(scaled_validation_set))
xgB_accuracy = classification_metrics(groundTruth, xgb_valid_predict)
print('xgB_accuracy:', xgB_accuracy)

Confusion Matrix:

[[33459 17044]
 [ 5647  5132]]

Accuracy:  0.6297281420319181

Classification report:

              precision    recall  f1-score   support

           0       0.86      0.66      0.75     50503
           1       0.23      0.48      0.31     10779

    accuracy                           0.63     61282
   macro avg       0.54      0.57      0.53     61282
weighted avg       0.75      0.63      0.67     61282

xgB_accuracy: None


In [36]:
xgb_valid_predict

0
0      1
1      1
2      1
3      1
4      1
...   ..
61277  0
61278  0
61279  0
61280  0
61281  1

[61282 rows x 1 columns]

In [37]:
groundTruth

important
116759          0
38261           0
3050            0
31609           0
15591           1
...           ...
34120           0
24396           0
215878          1
37376           0
93476           0

[61282 rows x 1 columns]

In [38]:
new_df=pd.DataFrame()

new_df['validation_set']=groundTruth['important']

new_df['prediction']=xgB.predict(scaled_validation_set)



new_df.head(60)

validation_set  prediction
116759               0           1
38261                0           1
3050                 0           1
31609                0           1
15591                1           1
300904               0           0
229509               0           1
55386                0           0
225235               0           1
214295               0           0
298430               1           0
39405                0           0
205154               0           1
3240                 1           0
255177               0           1
137340               1           0
6940                 0           1
212684               0           0
245174               0           0
280826               0           0
64319                0           0
160692               0           0
108537               0           0
255715               1           0
145692               0           0
255342               0           0
129798               0           0
199510               0           0
119567               1           1
20104                0           0
217080               1           0
141609               0           1
44942                0           1
241201               0           0
151143               0           0
197832               0           0
107381               0           0
287528               0           0
163067               0           0
305128               0           0
46947                0           1
181117               0           0
150420               0           1
211351               0           1
165892               1           1
228270               0           0
210686               1           1
82824                0           0
149634               0           0
268228               0           0
235230               0           0
176504               0           1
233609               0           0
269483               0           0
210944               0           1
25629                0           1
30327                0           0
84099                0           1
269701               0           0
262211               0           0

In [39]:
scale_pos_weight = [1,2,3,4,5,6,7,8,9,10]
for i in scale_pos_weight:
    print('scale_pos_weight = {}: '.format(i))
    clf = XGBClassifier(scale_pos_weight=i)
    clf.fit(x_train, y_train)
    predict = clf.predict(x_test)
    proba = clf.predict_proba(x_test)
    cm = confusion_matrix(y_test, predict)
    print(accuracy_score(y_test, predict))
    print('Confusion Matrix: \n', cm)
    print('--------------------')
    print('No : %', round(100 * (cm[0][0]/(cm[0][0]+cm[0][1]))))
    print('Yes : %', round(100* (cm[1][1]/(cm[1][0]+cm[1][1]))))
    print('---------------------------------------------------------')

scale_pos_weight = 1: 
0.8238660947177135
Confusion Matrix: 
 [[65958   608]
 [13640   687]]
--------------------
No : % 99.0
Yes : % 5.0
---------------------------------------------------------
scale_pos_weight = 2: 
0.8129875267328446
Confusion Matrix: 
 [[63871  2695]
 [12433  1894]]
--------------------
No : % 96.0
Yes : % 13.0
---------------------------------------------------------
scale_pos_weight = 3: 
0.7729346173340091
Confusion Matrix: 
 [[59029  7537]
 [10831  3496]]
--------------------
No : % 89.0
Yes : % 24.0
---------------------------------------------------------
scale_pos_weight = 4: 
0.7045232591200722
Confusion Matrix: 
 [[51327 15239]
 [ 8663  5664]]
--------------------
No : % 77.0
Yes : % 40.0
---------------------------------------------------------
scale_pos_weight = 5: 
0.6024872362256314
Confusion Matrix: 
 [[40822 25744]
 [ 6412  7915]]
--------------------
No : % 61.0
Yes : % 55.0
---------------------------------------------------------
scale_pos_weight

In [40]:
# knC = KNeighborsClassifier(n_neighbors=6)
# knC.fit(x_train, y_train) 
# knC_pred = knC.predict(x_test)

# classification_metrics(y_test, knC_pred)

In [41]:
lgbm = LGBMClassifier(scale_pos_weight = 5, random_state=0)
lgbm.fit(x_train, y_train)
lgbm_pred = lgbm.predict(x_test)

classification_metrics(y_test, lgbm_pred)

Confusion Matrix:

[[42122 24444]
 [ 6713  7614]]

Accuracy:  0.6148368832902723

Classification report:

              precision    recall  f1-score   support

           0       0.86      0.63      0.73     66566
           1       0.24      0.53      0.33     14327

    accuracy                           0.61     80893
   macro avg       0.55      0.58      0.53     80893
weighted avg       0.75      0.61      0.66     80893



In [42]:
predict = pd.DataFrame(data=lgbm.predict(scaled_validation_set))
lgbm_accuracy = classification_metrics(groundTruth, predict)
print('lgbm_accuracy:', lgbm_accuracy)

Confusion Matrix:

[[31843 18660]
 [ 5012  5767]]

Accuracy:  0.6137201788453379

Classification report:

              precision    recall  f1-score   support

           0       0.86      0.63      0.73     50503
           1       0.24      0.54      0.33     10779

    accuracy                           0.61     61282
   macro avg       0.55      0.58      0.53     61282
weighted avg       0.75      0.61      0.66     61282

lgbm_accuracy: None


In [43]:
gauss = GaussianNB()
gauss = gauss.fit(x_train, y_train)
gauss_pred = gauss.predict(x_test)

classification_metrics(y_test, gauss_pred)

Confusion Matrix:

[[52114 14452]
 [ 9715  4612]]

Accuracy:  0.7012473267155378

Classification report:

              precision    recall  f1-score   support

           0       0.84      0.78      0.81     66566
           1       0.24      0.32      0.28     14327

    accuracy                           0.70     80893
   macro avg       0.54      0.55      0.54     80893
weighted avg       0.74      0.70      0.72     80893



In [44]:
predict = pd.DataFrame(data=gauss.predict(scaled_validation_set))
gauss_accuracy = classification_metrics(groundTruth, predict)
    
print('gauss_accuracy:', gauss_accuracy)

Confusion Matrix:

[[39685 10818]
 [ 7247  3532]]

Accuracy:  0.705215234489736

Classification report:

              precision    recall  f1-score   support

           0       0.85      0.79      0.81     50503
           1       0.25      0.33      0.28     10779

    accuracy                           0.71     61282
   macro avg       0.55      0.56      0.55     61282
weighted avg       0.74      0.71      0.72     61282

gauss_accuracy: None


In [45]:
from sklearn.ensemble import GradientBoostingClassifier

gbC = GradientBoostingClassifier(random_state=0, n_estimators=10)
gbC.fit(x_train, y_train)
predict = pd.DataFrame(data=gbC.predict(x_test), index = x_test.index)
classification_metrics(y_test, predict)


Confusion Matrix:

[[66566     0]
 [14327     0]]

Accuracy:  0.8228894960008901

Classification report:

              precision    recall  f1-score   support

           0       0.82      1.00      0.90     66566
           1       0.00      0.00      0.00     14327

    accuracy                           0.82     80893
   macro avg       0.41      0.50      0.45     80893
weighted avg       0.68      0.82      0.74     80893



/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [46]:
predict = pd.DataFrame(data=gbC.predict(scaled_validation_set))
gbC_accuracy = classification_metrics(groundTruth, predict)
print('gbC_accuracy:', gbC_accuracy)

/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Confusion Matrix:

[[50503     0]
 [10779     0]]

Accuracy:  0.8241082210110636

Classification report:

              precision    recall  f1-score   support

           0       0.82      1.00      0.90     50503
           1       0.00      0.00      0.00     10779

    accuracy                           0.82     61282
   macro avg       0.41      0.50      0.45     61282
weighted avg       0.68      0.82      0.74     61282

gbC_accuracy: None


In [47]:
from sklearn.ensemble import AdaBoostClassifier

abC = AdaBoostClassifier(random_state=0, n_estimators=10, learning_rate=0.9)
abC.fit(x_train, y_train)
predict = pd.DataFrame(data=abC.predict(x_test), index = x_test.index)
classification_metrics(y_test, predict)


Confusion Matrix:

[[66566     0]
 [14327     0]]

Accuracy:  0.8228894960008901

Classification report:

              precision    recall  f1-score   support

           0       0.82      1.00      0.90     66566
           1       0.00      0.00      0.00     14327

    accuracy                           0.82     80893
   macro avg       0.41      0.50      0.45     80893
weighted avg       0.68      0.82      0.74     80893



/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [48]:
predict = pd.DataFrame(data=abC.predict(scaled_validation_set))
abC_accuracy = classification_metrics(groundTruth, predict)
print('abC_accuracy:', abC_accuracy)

Confusion Matrix:

[[50503     0]
 [10779     0]]

Accuracy:  0.8241082210110636

Classification report:

              precision    recall  f1-score   support

           0       0.82      1.00      0.90     50503
           1       0.00      0.00      0.00     10779

    accuracy                           0.82     61282
   macro avg       0.41      0.50      0.45     61282
weighted avg       0.68      0.82      0.74     61282

abC_accuracy: None


/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [49]:
from sklearn.ensemble import ExtraTreesClassifier
etC = ExtraTreesClassifier(random_state=0, n_estimators=50)

etC.fit(x_train, y_train)
predict = pd.DataFrame(data=etC.predict(x_test))
classification_metrics(y_test, predict)

Confusion Matrix:

[[60682  5884]
 [12328  1999]]

Accuracy:  0.7748630907495087

Classification report:

              precision    recall  f1-score   support

           0       0.83      0.91      0.87     66566
           1       0.25      0.14      0.18     14327

    accuracy                           0.77     80893
   macro avg       0.54      0.53      0.52     80893
weighted avg       0.73      0.77      0.75     80893



In [50]:
predict = pd.DataFrame(data=etC.predict(scaled_validation_set))
etC_accuracy = classification_metrics(groundTruth, predict)
print('etC_accuracy:', etC_accuracy)

Confusion Matrix:

[[46192  4311]
 [ 9238  1541]]

Accuracy:  0.7789073463659802

Classification report:

              precision    recall  f1-score   support

           0       0.83      0.91      0.87     50503
           1       0.26      0.14      0.19     10779

    accuracy                           0.78     61282
   macro avg       0.55      0.53      0.53     61282
weighted avg       0.73      0.78      0.75     61282

etC_accuracy: None


In [51]:
from sklearn.ensemble import RandomForestClassifier
rfC = RandomForestClassifier(criterion='entropy', max_depth= 8, max_leaf_nodes=5, min_samples_leaf=5, n_estimators= 100, random_state=0, class_weight='balanced')

rfC.fit(x_train, y_train)
predict = pd.DataFrame(data=rfC.predict(x_test))
classification_metrics(y_test, predict)

Confusion Matrix:

[[48677 17889]
 [ 8856  5471]]

Accuracy:  0.6693780673235015

Classification report:

              precision    recall  f1-score   support

           0       0.85      0.73      0.78     66566
           1       0.23      0.38      0.29     14327

    accuracy                           0.67     80893
   macro avg       0.54      0.56      0.54     80893
weighted avg       0.74      0.67      0.70     80893



In [52]:
predict = pd.DataFrame(data=rfC.predict(scaled_validation_set))
rfC_accuracy = classification_metrics(groundTruth, predict)
print('rfC_accuracy:', rfC_accuracy)

Confusion Matrix:

[[36810 13693]
 [ 6568  4211]]

Accuracy:  0.66938089487941

Classification report:

              precision    recall  f1-score   support

           0       0.85      0.73      0.78     50503
           1       0.24      0.39      0.29     10779

    accuracy                           0.67     61282
   macro avg       0.54      0.56      0.54     61282
weighted avg       0.74      0.67      0.70     61282

rfC_accuracy: None
