In [59]:
#importing the necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno

In [60]:
#reading csv file from db
df = pd.read_csv('../input/boston-crime-data/crime.csv', encoding='latin-1')
df.head()

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


INCIDENT_NUMBER  OFFENSE_CODE  OFFENSE_CODE_GROUP  \
0      I182080058          2403  Disorderly Conduct   
1      I182080053          3201       Property Lost   
2      I182080052          2647               Other   
3      I182080051           413  Aggravated Assault   
4      I182080050          3122            Aircraft   

              OFFENSE_DESCRIPTION DISTRICT REPORTING_AREA SHOOTING  \
0            DISTURBING THE PEACE      E18            495      NaN   
1                 PROPERTY - LOST      D14            795      NaN   
2       THREATS TO DO BODILY HARM       B2            329      NaN   
3  ASSAULT - AGGRAVATED - BATTERY       A1             92      NaN   
4              AIRCRAFT INCIDENTS       A7             36      NaN   

      OCCURRED_ON_DATE  YEAR  MONTH DAY_OF_WEEK  HOUR    UCR_PART  \
0  2018-10-03 20:13:00  2018     10   Wednesday    20    Part Two   
1  2018-08-30 20:00:00  2018      8    Thursday    20  Part Three   
2  2018-10-03 19:20:00  2018     10   Wednesday    19    Part Two   
3  2018-10-03 20:00:00  2018     10   Wednesday    20    Part One   
4  2018-10-03 20:49:00  2018     10   Wednesday    20  Part Three   

         STREET        Lat       Long                     Location  
0  ARLINGTON ST  42.262608 -71.121186  (42.26260773, -71.12118637)  
1    ALLSTON ST  42.352111 -71.135311  (42.35211146, -71.13531147)  
2      DEVON ST  42.308126 -71.076930  (42.30812619, -71.07692974)  
3  CAMBRIDGE ST  42.359454 -71.059648  (42.35945371, -71.05964817)  
4   PRESCOTT ST  42.375258 -71.024663  (42.37525782, -71.02466343)

# Feature Engineering

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 327820 entries, 0 to 327819
Data columns (total 17 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   INCIDENT_NUMBER      327820 non-null  object 
 1   OFFENSE_CODE         327820 non-null  int64  
 2   OFFENSE_CODE_GROUP   327820 non-null  object 
 3   OFFENSE_DESCRIPTION  327820 non-null  object 
 4   DISTRICT             326046 non-null  object 
 5   REPORTING_AREA       327820 non-null  object 
 6   SHOOTING             1055 non-null    object 
 7   OCCURRED_ON_DATE     327820 non-null  object 
 8   YEAR                 327820 non-null  int64  
 9   MONTH                327820 non-null  int64  
 10  DAY_OF_WEEK          327820 non-null  object 
 11  HOUR                 327820 non-null  int64  
 12  UCR_PART             327727 non-null  object 
 13  STREET               316843 non-null  object 
 14  Lat                  307188 non-null  float64
 15  Long             

In [63]:
#filling null values in shooting feature as '0' and replacing 'Y' values with '1'
df['SHOOTING']= df['SHOOTING'].fillna(value='0')
df['SHOOTING'] = df['SHOOTING'].replace('Y',1)
df

INCIDENT_NUMBER  OFFENSE_CODE  OFFENSE_CODE_GROUP  \
0           I182080058          2403  Disorderly Conduct   
1           I182080053          3201       Property Lost   
2           I182080052          2647               Other   
3           I182080051           413  Aggravated Assault   
4           I182080050          3122            Aircraft   
...                ...           ...                 ...   
327815   I050310906-00          3125     Warrant Arrests   
327816   I030217815-08           111            Homicide   
327817   I030217815-08          3125     Warrant Arrests   
327818   I010370257-00          3125     Warrant Arrests   
327819       142052550          3125     Warrant Arrests   

                        OFFENSE_DESCRIPTION DISTRICT REPORTING_AREA SHOOTING  \
0                      DISTURBING THE PEACE      E18            495        0   
1                           PROPERTY - LOST      D14            795        0   
2                 THREATS TO DO BODILY HARM       B2            329        0   
3            ASSAULT - AGGRAVATED - BATTERY       A1             92        0   
4                        AIRCRAFT INCIDENTS       A7             36        0   
...                                     ...      ...            ...      ...   
327815                       WARRANT ARREST       D4            285        0   
327816  MURDER, NON-NEGLIGIENT MANSLAUGHTER      E18            520        0   
327817                       WARRANT ARREST      E18            520        0   
327818                       WARRANT ARREST      E13            569        0   
327819                       WARRANT ARREST       D4            903        0   

           OCCURRED_ON_DATE  YEAR  MONTH DAY_OF_WEEK  HOUR    UCR_PART  \
0       2018-10-03 20:13:00  2018     10   Wednesday    20    Part Two   
1       2018-08-30 20:00:00  2018      8    Thursday    20  Part Three   
2       2018-10-03 19:20:00  2018     10   Wednesday    19    Part Two   
3       2018-10-03 20:00:00  2018     10   Wednesday    20    Part One   
4       2018-10-03 20:49:00  2018     10   Wednesday    20  Part Three   
...                     ...   ...    ...         ...   ...         ...   
327815  2016-06-05 17:25:00  2016      6      Sunday    17  Part Three   
327816  2015-07-09 13:38:00  2015      7    Thursday    13    Part One   
327817  2015-07-09 13:38:00  2015      7    Thursday    13  Part Three   
327818  2016-05-31 19:35:00  2016      5     Tuesday    19  Part Three   
327819  2015-06-22 00:12:00  2015      6      Monday     0  Part Three   

                   STREET        Lat       Long                     Location  
0            ARLINGTON ST  42.262608 -71.121186  (42.26260773, -71.12118637)  
1              ALLSTON ST  42.352111 -71.135311  (42.35211146, -71.13531147)  
2                DEVON ST  42.308126 -71.076930  (42.30812619, -71.07692974)  
3            CAMBRIDGE ST  42.359454 -71.059648  (42.35945371, -71.05964817)  
4             PRESCOTT ST  42.375258 -71.024663  (42.37525782, -71.02466343)  
...                   ...        ...        ...                          ...  
327815        COVENTRY ST  42.336951 -71.085748  (42.33695098, -71.08574813)  
327816           RIVER ST  42.255926 -71.123172  (42.25592648, -71.12317207)  
327817           RIVER ST  42.255926 -71.123172  (42.25592648, -71.12317207)  
327818  NEW WASHINGTON ST  42.302333 -71.111565  (42.30233307, -71.11156487)  
327819      WASHINGTON ST  42.333839 -71.080290  (42.33383935, -71.08029038)  

[327820 rows x 17 columns]

In [64]:
#droping Nan values from Lat and Long 
#droping from Lat and Long with the values of '-1' --removing outliers
# it reduced the number of rows from 327.727 to 306.320
df = df.dropna(subset = ['Lat', 'Long'])
df = df[df['Lat'] > 0]
df

INCIDENT_NUMBER  OFFENSE_CODE  OFFENSE_CODE_GROUP  \
0           I182080058          2403  Disorderly Conduct   
1           I182080053          3201       Property Lost   
2           I182080052          2647               Other   
3           I182080051           413  Aggravated Assault   
4           I182080050          3122            Aircraft   
...                ...           ...                 ...   
327815   I050310906-00          3125     Warrant Arrests   
327816   I030217815-08           111            Homicide   
327817   I030217815-08          3125     Warrant Arrests   
327818   I010370257-00          3125     Warrant Arrests   
327819       142052550          3125     Warrant Arrests   

                        OFFENSE_DESCRIPTION DISTRICT REPORTING_AREA SHOOTING  \
0                      DISTURBING THE PEACE      E18            495        0   
1                           PROPERTY - LOST      D14            795        0   
2                 THREATS TO DO BODILY HARM       B2            329        0   
3            ASSAULT - AGGRAVATED - BATTERY       A1             92        0   
4                        AIRCRAFT INCIDENTS       A7             36        0   
...                                     ...      ...            ...      ...   
327815                       WARRANT ARREST       D4            285        0   
327816  MURDER, NON-NEGLIGIENT MANSLAUGHTER      E18            520        0   
327817                       WARRANT ARREST      E18            520        0   
327818                       WARRANT ARREST      E13            569        0   
327819                       WARRANT ARREST       D4            903        0   

           OCCURRED_ON_DATE  YEAR  MONTH DAY_OF_WEEK  HOUR    UCR_PART  \
0       2018-10-03 20:13:00  2018     10   Wednesday    20    Part Two   
1       2018-08-30 20:00:00  2018      8    Thursday    20  Part Three   
2       2018-10-03 19:20:00  2018     10   Wednesday    19    Part Two   
3       2018-10-03 20:00:00  2018     10   Wednesday    20    Part One   
4       2018-10-03 20:49:00  2018     10   Wednesday    20  Part Three   
...                     ...   ...    ...         ...   ...         ...   
327815  2016-06-05 17:25:00  2016      6      Sunday    17  Part Three   
327816  2015-07-09 13:38:00  2015      7    Thursday    13    Part One   
327817  2015-07-09 13:38:00  2015      7    Thursday    13  Part Three   
327818  2016-05-31 19:35:00  2016      5     Tuesday    19  Part Three   
327819  2015-06-22 00:12:00  2015      6      Monday     0  Part Three   

                   STREET        Lat       Long                     Location  
0            ARLINGTON ST  42.262608 -71.121186  (42.26260773, -71.12118637)  
1              ALLSTON ST  42.352111 -71.135311  (42.35211146, -71.13531147)  
2                DEVON ST  42.308126 -71.076930  (42.30812619, -71.07692974)  
3            CAMBRIDGE ST  42.359454 -71.059648  (42.35945371, -71.05964817)  
4             PRESCOTT ST  42.375258 -71.024663  (42.37525782, -71.02466343)  
...                   ...        ...        ...                          ...  
327815        COVENTRY ST  42.336951 -71.085748  (42.33695098, -71.08574813)  
327816           RIVER ST  42.255926 -71.123172  (42.25592648, -71.12317207)  
327817           RIVER ST  42.255926 -71.123172  (42.25592648, -71.12317207)  
327818  NEW WASHINGTON ST  42.302333 -71.111565  (42.30233307, -71.11156487)  
327819      WASHINGTON ST  42.333839 -71.080290  (42.33383935, -71.08029038)  

[306413 rows x 17 columns]

In [65]:
df.describe()

OFFENSE_CODE           YEAR          MONTH           HOUR  \
count  306413.000000  306413.000000  306413.000000  306413.000000   
mean     2296.613835    2016.591248       6.674469      13.122717   
std      1182.763063       1.013933       3.258638       6.277278   
min       111.000000    2015.000000       1.000000       0.000000   
25%       802.000000    2016.000000       4.000000       9.000000   
50%      2907.000000    2017.000000       7.000000      14.000000   
75%      3201.000000    2017.000000       9.000000      18.000000   
max      3831.000000    2018.000000      12.000000      23.000000   

                 Lat           Long  
count  306413.000000  306413.000000  
mean       42.322292     -71.082841  
std         0.031859       0.029744  
min        42.232413     -71.178674  
25%        42.297555     -71.097189  
50%        42.325646     -71.077550  
75%        42.348624     -71.062563  
max        42.395042     -70.963676

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 306413 entries, 0 to 327819
Data columns (total 17 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   INCIDENT_NUMBER      306413 non-null  object 
 1   OFFENSE_CODE         306413 non-null  int64  
 2   OFFENSE_CODE_GROUP   306413 non-null  object 
 3   OFFENSE_DESCRIPTION  306413 non-null  object 
 4   DISTRICT             305542 non-null  object 
 5   REPORTING_AREA       306413 non-null  object 
 6   SHOOTING             306413 non-null  object 
 7   OCCURRED_ON_DATE     306413 non-null  object 
 8   YEAR                 306413 non-null  int64  
 9   MONTH                306413 non-null  int64  
 10  DAY_OF_WEEK          306413 non-null  object 
 11  HOUR                 306413 non-null  int64  
 12  UCR_PART             306320 non-null  object 
 13  STREET               304631 non-null  object 
 14  Lat                  306413 non-null  float64
 15  Long             

In [67]:
#creating date_time format and drop occured_on_date column
df["OCCURRED_ON_DATE"]=pd.to_datetime(df["OCCURRED_ON_DATE"],infer_datetime_format=True)
df["OCCURRED_DAY"]=df["OCCURRED_ON_DATE"].apply(lambda x: x.date())
df = df.drop(['OCCURRED_ON_DATE'],axis = 1)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 306413 entries, 0 to 327819
Data columns (total 17 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   INCIDENT_NUMBER      306413 non-null  object 
 1   OFFENSE_CODE         306413 non-null  int64  
 2   OFFENSE_CODE_GROUP   306413 non-null  object 
 3   OFFENSE_DESCRIPTION  306413 non-null  object 
 4   DISTRICT             305542 non-null  object 
 5   REPORTING_AREA       306413 non-null  object 
 6   SHOOTING             306413 non-null  object 
 7   YEAR                 306413 non-null  int64  
 8   MONTH                306413 non-null  int64  
 9   DAY_OF_WEEK          306413 non-null  object 
 10  HOUR                 306413 non-null  int64  
 11  UCR_PART             306320 non-null  object 
 12  STREET               304631 non-null  object 
 13  Lat                  306413 non-null  float64
 14  Long                 306413 non-null  float64
 15  Location         

In [68]:
#for model 1 creating a dataframe which name is df_m_1, sorting the dates and drop na rows from DISTRICT feature
df_m_1 = df.copy()
df_m_1 = df_m_1.sort_values(by =['OCCURRED_DAY'], ascending=False)
df_m_1['OCCURRED_DAY']= pd.to_datetime(df_m_1['OCCURRED_DAY'])
df_m_1 = df_m_1.dropna(subset=['DISTRICT'])
df_m_1

INCIDENT_NUMBER  OFFENSE_CODE               OFFENSE_CODE_GROUP  \
0           I182080058          2403               Disorderly Conduct   
166         I182079875          3801  Motor Vehicle Accident Response   
146         I182079895          3410                            Towed   
148         I182079893          1402                        Vandalism   
149         I182079892          1402                        Vandalism   
...                ...           ...                              ...   
327337      I152049637           802                   Simple Assault   
327338      I152049635          3831  Motor Vehicle Accident Response   
327339      I152049634          1842                   Drug Violation   
327340      I152049634          3125                  Warrant Arrests   
327308      I152049683           522             Residential Burglary   

                          OFFENSE_DESCRIPTION DISTRICT REPORTING_AREA  \
0                        DISTURBING THE PEACE      E18            495   
166                      M/V ACCIDENT - OTHER      D14            783   
146                       TOWED MOTOR VEHICLE       B2            237   
148                                 VANDALISM      C11            344   
149                                 VANDALISM      C11            368   
...                                       ...      ...            ...   
327337               ASSAULT SIMPLE - BATTERY      C11            817   
327338  M/V - LEAVING SCENE - PROPERTY DAMAGE       B2            602   
327339   DRUGS - POSS CLASS A - HEROIN, ETC.       E13            569   
327340                         WARRANT ARREST      E13            569   
327308      BURGLARY - RESIDENTIAL - NO FORCE       E5            686   

       SHOOTING  YEAR  MONTH DAY_OF_WEEK  HOUR    UCR_PART            STREET  \
0             0  2018     10   Wednesday    20    Part Two      ARLINGTON ST   
166           0  2018     10   Wednesday    11  Part Three  COMMONWEALTH AVE   
146           0  2018     10   Wednesday    11  Part Three        EASTMAN ST   
148           0  2018     10   Wednesday    12    Part Two        BOWDOIN ST   
149           0  2018     10   Wednesday     7    Part Two      NEPONSET AVE   
...         ...   ...    ...         ...   ...         ...               ...   
327337        0  2015      6      Monday    15    Part Two        TALBOT AVE   
327338        0  2015      6      Monday    14  Part Three        TREMONT ST   
327339        0  2015      6      Monday    15    Part Two       BROOKLEY RD   
327340        0  2015      6      Monday    15  Part Three       BROOKLEY RD   
327308        0  2015      6      Monday    17    Part One       COLBERG AVE   

              Lat       Long                     Location OCCURRED_DAY  
0       42.262608 -71.121186  (42.26260773, -71.12118637)   2018-10-03  
166     42.348886 -71.140074  (42.34888559, -71.14007361)   2018-10-03  
146     42.319860 -71.064341  (42.31986040, -71.06434120)   2018-10-03  
148     42.300308 -71.072064  (42.30030819, -71.07206425)   2018-10-03  
149     42.293836 -71.051574  (42.29383600, -71.05157448)   2018-10-03  
...           ...        ...                          ...          ...  
327337  42.288638 -71.066316  (42.28863812, -71.06631579)   2015-06-15  
327338  42.333669 -71.103335  (42.33366866, -71.10333486)   2015-06-15  
327339  42.304816 -71.109118  (42.30481623, -71.10911850)   2015-06-15  
327340  42.304816 -71.109118  (42.30481623, -71.10911850)   2015-06-15  
327308  42.283113 -71.143922  (42.28311294, -71.14392166)   2015-06-15  

[305542 rows x 17 columns]

In [69]:
df_m_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 305542 entries, 0 to 327308
Data columns (total 17 columns):
 #   Column               Non-Null Count   Dtype         
---  ------               --------------   -----         
 0   INCIDENT_NUMBER      305542 non-null  object        
 1   OFFENSE_CODE         305542 non-null  int64         
 2   OFFENSE_CODE_GROUP   305542 non-null  object        
 3   OFFENSE_DESCRIPTION  305542 non-null  object        
 4   DISTRICT             305542 non-null  object        
 5   REPORTING_AREA       305542 non-null  object        
 6   SHOOTING             305542 non-null  object        
 7   YEAR                 305542 non-null  int64         
 8   MONTH                305542 non-null  int64         
 9   DAY_OF_WEEK          305542 non-null  object        
 10  HOUR                 305542 non-null  int64         
 11  UCR_PART             305449 non-null  object        
 12  STREET               304596 non-null  object        
 13  Lat           

In [70]:
df['DAY_OF_WEEK'].value_counts()

Friday       46494
Wednesday    45059
Thursday     44677
Tuesday      44517
Monday       43919
Saturday     42873
Sunday       38874
Name: DAY_OF_WEEK, dtype: int64

In [71]:
# day_of_week label encoding

df_m_1['DAY_OF_WEEK'] = df_m_1['DAY_OF_WEEK'].map({
    'Tuesday':4, 
    'Saturday':2, 
    'Monday':3, 
    'Sunday':1, 
    'Thursday':5, 
    'Wednesday':6,
    'Friday':7
})
df_m_1

INCIDENT_NUMBER  OFFENSE_CODE               OFFENSE_CODE_GROUP  \
0           I182080058          2403               Disorderly Conduct   
166         I182079875          3801  Motor Vehicle Accident Response   
146         I182079895          3410                            Towed   
148         I182079893          1402                        Vandalism   
149         I182079892          1402                        Vandalism   
...                ...           ...                              ...   
327337      I152049637           802                   Simple Assault   
327338      I152049635          3831  Motor Vehicle Accident Response   
327339      I152049634          1842                   Drug Violation   
327340      I152049634          3125                  Warrant Arrests   
327308      I152049683           522             Residential Burglary   

                          OFFENSE_DESCRIPTION DISTRICT REPORTING_AREA  \
0                        DISTURBING THE PEACE      E18            495   
166                      M/V ACCIDENT - OTHER      D14            783   
146                       TOWED MOTOR VEHICLE       B2            237   
148                                 VANDALISM      C11            344   
149                                 VANDALISM      C11            368   
...                                       ...      ...            ...   
327337               ASSAULT SIMPLE - BATTERY      C11            817   
327338  M/V - LEAVING SCENE - PROPERTY DAMAGE       B2            602   
327339   DRUGS - POSS CLASS A - HEROIN, ETC.       E13            569   
327340                         WARRANT ARREST      E13            569   
327308      BURGLARY - RESIDENTIAL - NO FORCE       E5            686   

       SHOOTING  YEAR  MONTH  DAY_OF_WEEK  HOUR    UCR_PART            STREET  \
0             0  2018     10            6    20    Part Two      ARLINGTON ST   
166           0  2018     10            6    11  Part Three  COMMONWEALTH AVE   
146           0  2018     10            6    11  Part Three        EASTMAN ST   
148           0  2018     10            6    12    Part Two        BOWDOIN ST   
149           0  2018     10            6     7    Part Two      NEPONSET AVE   
...         ...   ...    ...          ...   ...         ...               ...   
327337        0  2015      6            3    15    Part Two        TALBOT AVE   
327338        0  2015      6            3    14  Part Three        TREMONT ST   
327339        0  2015      6            3    15    Part Two       BROOKLEY RD   
327340        0  2015      6            3    15  Part Three       BROOKLEY RD   
327308        0  2015      6            3    17    Part One       COLBERG AVE   

              Lat       Long                     Location OCCURRED_DAY  
0       42.262608 -71.121186  (42.26260773, -71.12118637)   2018-10-03  
166     42.348886 -71.140074  (42.34888559, -71.14007361)   2018-10-03  
146     42.319860 -71.064341  (42.31986040, -71.06434120)   2018-10-03  
148     42.300308 -71.072064  (42.30030819, -71.07206425)   2018-10-03  
149     42.293836 -71.051574  (42.29383600, -71.05157448)   2018-10-03  
...           ...        ...                          ...          ...  
327337  42.288638 -71.066316  (42.28863812, -71.06631579)   2015-06-15  
327338  42.333669 -71.103335  (42.33366866, -71.10333486)   2015-06-15  
327339  42.304816 -71.109118  (42.30481623, -71.10911850)   2015-06-15  
327340  42.304816 -71.109118  (42.30481623, -71.10911850)   2015-06-15  
327308  42.283113 -71.143922  (42.28311294, -71.14392166)   2015-06-15  

[305542 rows x 17 columns]

In [72]:
# df_m_1['UCR_PART'] = df_m_1['UCR_PART'].map({
#     'Part One':3, 
#     'Part Two':2, 
#     'Part Three':1, 
#     'Other':0, 

# })
# df_m_1

In [73]:
# creating summer, HOUR_12_16_17_18_19, HOUR_3_4_5_6(least hours), RIVER | CENTRE (most occured streets), RA (most occured reporting areas) features which have the highest crime occured

df_m_1['Summer']=0
df_m_1['Summer']=df_m_1["MONTH"].apply(lambda x: 1 if x==6 or x==7 or x==8 or x==9 else 0)


df_m_1['HOUR_12_16_17_18_19']=0
df_m_1['HOUR_12_16_17_18_19']=df_m_1["HOUR"].apply(lambda x: 1 if x==12 or x==16 or x==17 or x==18 or x==19 else 0)
df_m_1

df_m_1['HOUR_3_4_5_6']=0
df_m_1['HOUR_3_4_5_6']=df_m_1["HOUR"].apply(lambda x: 1 if x==3 or x==4 or x==5 or x==6 else 0)
df_m_1

df_m_1['RIVER | CENTRE'] = 0
df_m_1['RIVER | CENTRE'] = df_m_1["STREET"].apply(lambda x: 0 if x=='RIVER ST' or x=='CENTRE ST' else 1)
df_m_1

df_m_1['RA'] = 0
df_m_1['RA'] = df_m_1["REPORTING_AREA"].apply(lambda x: 1 if x=='143' or x=='134' or x=='186' or x=='111' else 1)
df_m_1

INCIDENT_NUMBER  OFFENSE_CODE               OFFENSE_CODE_GROUP  \
0           I182080058          2403               Disorderly Conduct   
166         I182079875          3801  Motor Vehicle Accident Response   
146         I182079895          3410                            Towed   
148         I182079893          1402                        Vandalism   
149         I182079892          1402                        Vandalism   
...                ...           ...                              ...   
327337      I152049637           802                   Simple Assault   
327338      I152049635          3831  Motor Vehicle Accident Response   
327339      I152049634          1842                   Drug Violation   
327340      I152049634          3125                  Warrant Arrests   
327308      I152049683           522             Residential Burglary   

                          OFFENSE_DESCRIPTION DISTRICT REPORTING_AREA  \
0                        DISTURBING THE PEACE      E18            495   
166                      M/V ACCIDENT - OTHER      D14            783   
146                       TOWED MOTOR VEHICLE       B2            237   
148                                 VANDALISM      C11            344   
149                                 VANDALISM      C11            368   
...                                       ...      ...            ...   
327337               ASSAULT SIMPLE - BATTERY      C11            817   
327338  M/V - LEAVING SCENE - PROPERTY DAMAGE       B2            602   
327339   DRUGS - POSS CLASS A - HEROIN, ETC.       E13            569   
327340                         WARRANT ARREST      E13            569   
327308      BURGLARY - RESIDENTIAL - NO FORCE       E5            686   

       SHOOTING  YEAR  MONTH  DAY_OF_WEEK  ...            STREET        Lat  \
0             0  2018     10            6  ...      ARLINGTON ST  42.262608   
166           0  2018     10            6  ...  COMMONWEALTH AVE  42.348886   
146           0  2018     10            6  ...        EASTMAN ST  42.319860   
148           0  2018     10            6  ...        BOWDOIN ST  42.300308   
149           0  2018     10            6  ...      NEPONSET AVE  42.293836   
...         ...   ...    ...          ...  ...               ...        ...   
327337        0  2015      6            3  ...        TALBOT AVE  42.288638   
327338        0  2015      6            3  ...        TREMONT ST  42.333669   
327339        0  2015      6            3  ...       BROOKLEY RD  42.304816   
327340        0  2015      6            3  ...       BROOKLEY RD  42.304816   
327308        0  2015      6            3  ...       COLBERG AVE  42.283113   

             Long                     Location  OCCURRED_DAY Summer  \
0      -71.121186  (42.26260773, -71.12118637)    2018-10-03      0   
166    -71.140074  (42.34888559, -71.14007361)    2018-10-03      0   
146    -71.064341  (42.31986040, -71.06434120)    2018-10-03      0   
148    -71.072064  (42.30030819, -71.07206425)    2018-10-03      0   
149    -71.051574  (42.29383600, -71.05157448)    2018-10-03      0   
...           ...                          ...           ...    ...   
327337 -71.066316  (42.28863812, -71.06631579)    2015-06-15      1   
327338 -71.103335  (42.33366866, -71.10333486)    2015-06-15      1   
327339 -71.109118  (42.30481623, -71.10911850)    2015-06-15      1   
327340 -71.109118  (42.30481623, -71.10911850)    2015-06-15      1   
327308 -71.143922  (42.28311294, -71.14392166)    2015-06-15      1   

       HOUR_12_16_17_18_19  HOUR_3_4_5_6  RIVER | CENTRE  RA  
0                        0             0               1   1  
166                      0             0               1   1  
146                      0             0               1   1  
148                      1             0               1   1  
149                      0             0               1   1  
...                    ...           ...             ...  ..  
327337    

In [74]:
#one-hot encoding for district and UCR_Part columns
def get_dummies(dataframe):
    
    #for DISTRICT column
    
#     DISTRICT = pd.get_dummies(dataframe.DISTRICT, prefix = 'DIS')
#     dataframe = pd.concat([dataframe,DISTRICT],axis = 1)
#     dataframe = dataframe.drop(['DISTRICT'],axis = 1)
    
    #for UCR PART column
    
    UCR_PART = pd.get_dummies(dataframe.UCR_PART, prefix = 'UCR')
    dataframe = pd.concat([dataframe,UCR_PART],axis = 1)
    dataframe = dataframe.drop(['UCR_PART'],axis = 1)
    
    return dataframe
df_m_1 =get_dummies(df_m_1)
df_m_1

INCIDENT_NUMBER  OFFENSE_CODE               OFFENSE_CODE_GROUP  \
0           I182080058          2403               Disorderly Conduct   
166         I182079875          3801  Motor Vehicle Accident Response   
146         I182079895          3410                            Towed   
148         I182079893          1402                        Vandalism   
149         I182079892          1402                        Vandalism   
...                ...           ...                              ...   
327337      I152049637           802                   Simple Assault   
327338      I152049635          3831  Motor Vehicle Accident Response   
327339      I152049634          1842                   Drug Violation   
327340      I152049634          3125                  Warrant Arrests   
327308      I152049683           522             Residential Burglary   

                          OFFENSE_DESCRIPTION DISTRICT REPORTING_AREA  \
0                        DISTURBING THE PEACE      E18            495   
166                      M/V ACCIDENT - OTHER      D14            783   
146                       TOWED MOTOR VEHICLE       B2            237   
148                                 VANDALISM      C11            344   
149                                 VANDALISM      C11            368   
...                                       ...      ...            ...   
327337               ASSAULT SIMPLE - BATTERY      C11            817   
327338  M/V - LEAVING SCENE - PROPERTY DAMAGE       B2            602   
327339   DRUGS - POSS CLASS A - HEROIN, ETC.       E13            569   
327340                         WARRANT ARREST      E13            569   
327308      BURGLARY - RESIDENTIAL - NO FORCE       E5            686   

       SHOOTING  YEAR  MONTH  DAY_OF_WEEK  ...  OCCURRED_DAY Summer  \
0             0  2018     10            6  ...    2018-10-03      0   
166           0  2018     10            6  ...    2018-10-03      0   
146           0  2018     10            6  ...    2018-10-03      0   
148           0  2018     10            6  ...    2018-10-03      0   
149           0  2018     10            6  ...    2018-10-03      0   
...         ...   ...    ...          ...  ...           ...    ...   
327337        0  2015      6            3  ...    2015-06-15      1   
327338        0  2015      6            3  ...    2015-06-15      1   
327339        0  2015      6            3  ...    2015-06-15      1   
327340        0  2015      6            3  ...    2015-06-15      1   
327308        0  2015      6            3  ...    2015-06-15      1   

        HOUR_12_16_17_18_19  HOUR_3_4_5_6 RIVER | CENTRE RA  UCR_Other  \
0                         0             0              1  1          0   
166                       0             0              1  1          0   
146                       0             0              1  1          0   
148                       1             0              1  1          0   
149                       0             0              1  1          0   
...                     ...           ...            ... ..        ...   
327337                    0             0              1  1          0   
327338                    0             0              1  1          0   
327339                    0             0              1  1          0   
327340                    0             0              1  1          0   
327308                    1             0              1  1          0   

        UCR_Part One  UCR_Part Three  UCR_Part Two  
0                  0               0             1  
166                0               1             0  
146                0               1             0  
148                0               0             1  
149                0               0             1  
...              ...             ...           ...  
327337             0               0             1  
327338             0               1             0  
327339             0              

In [75]:
df_m_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 305542 entries, 0 to 327308
Data columns (total 25 columns):
 #   Column               Non-Null Count   Dtype         
---  ------               --------------   -----         
 0   INCIDENT_NUMBER      305542 non-null  object        
 1   OFFENSE_CODE         305542 non-null  int64         
 2   OFFENSE_CODE_GROUP   305542 non-null  object        
 3   OFFENSE_DESCRIPTION  305542 non-null  object        
 4   DISTRICT             305542 non-null  object        
 5   REPORTING_AREA       305542 non-null  object        
 6   SHOOTING             305542 non-null  object        
 7   YEAR                 305542 non-null  int64         
 8   MONTH                305542 non-null  int64         
 9   DAY_OF_WEEK          305542 non-null  int64         
 10  HOUR                 305542 non-null  int64         
 11  STREET               304596 non-null  object        
 12  Lat                  305542 non-null  float64       
 13  Long          

In [76]:
df_m_1

INCIDENT_NUMBER  OFFENSE_CODE               OFFENSE_CODE_GROUP  \
0           I182080058          2403               Disorderly Conduct   
166         I182079875          3801  Motor Vehicle Accident Response   
146         I182079895          3410                            Towed   
148         I182079893          1402                        Vandalism   
149         I182079892          1402                        Vandalism   
...                ...           ...                              ...   
327337      I152049637           802                   Simple Assault   
327338      I152049635          3831  Motor Vehicle Accident Response   
327339      I152049634          1842                   Drug Violation   
327340      I152049634          3125                  Warrant Arrests   
327308      I152049683           522             Residential Burglary   

                          OFFENSE_DESCRIPTION DISTRICT REPORTING_AREA  \
0                        DISTURBING THE PEACE      E18            495   
166                      M/V ACCIDENT - OTHER      D14            783   
146                       TOWED MOTOR VEHICLE       B2            237   
148                                 VANDALISM      C11            344   
149                                 VANDALISM      C11            368   
...                                       ...      ...            ...   
327337               ASSAULT SIMPLE - BATTERY      C11            817   
327338  M/V - LEAVING SCENE - PROPERTY DAMAGE       B2            602   
327339   DRUGS - POSS CLASS A - HEROIN, ETC.       E13            569   
327340                         WARRANT ARREST      E13            569   
327308      BURGLARY - RESIDENTIAL - NO FORCE       E5            686   

       SHOOTING  YEAR  MONTH  DAY_OF_WEEK  ...  OCCURRED_DAY Summer  \
0             0  2018     10            6  ...    2018-10-03      0   
166           0  2018     10            6  ...    2018-10-03      0   
146           0  2018     10            6  ...    2018-10-03      0   
148           0  2018     10            6  ...    2018-10-03      0   
149           0  2018     10            6  ...    2018-10-03      0   
...         ...   ...    ...          ...  ...           ...    ...   
327337        0  2015      6            3  ...    2015-06-15      1   
327338        0  2015      6            3  ...    2015-06-15      1   
327339        0  2015      6            3  ...    2015-06-15      1   
327340        0  2015      6            3  ...    2015-06-15      1   
327308        0  2015      6            3  ...    2015-06-15      1   

        HOUR_12_16_17_18_19  HOUR_3_4_5_6 RIVER | CENTRE RA  UCR_Other  \
0                         0             0              1  1          0   
166                       0             0              1  1          0   
146                       0             0              1  1          0   
148                       1             0              1  1          0   
149                       0             0              1  1          0   
...                     ...           ...            ... ..        ...   
327337                    0             0              1  1          0   
327338                    0             0              1  1          0   
327339                    0             0              1  1          0   
327340                    0             0              1  1          0   
327308                    1             0              1  1          0   

        UCR_Part One  UCR_Part Three  UCR_Part Two  
0                  0               0             1  
166                0               1             0  
146                0               1             0  
148                0               0             1  
149                0               0             1  
...              ...             ...           ...  
327337             0               0             1  
327338             0               1             0  
327339             0              

In [77]:
#label encoding for district column

df_m_1['DISTRICT'] = df_m_1['DISTRICT'].map({
    'B3':1, 
    'E18':2, 
    'B2':3, 
    'E5':4, 
    'C6':5, 
    'D14':6, 
    'E13':7, 
    'C11':8, 
    'D4':9, 
    'A7':10, 
    'A1':11, 
    'A15':12
})

df_m_1

INCIDENT_NUMBER  OFFENSE_CODE               OFFENSE_CODE_GROUP  \
0           I182080058          2403               Disorderly Conduct   
166         I182079875          3801  Motor Vehicle Accident Response   
146         I182079895          3410                            Towed   
148         I182079893          1402                        Vandalism   
149         I182079892          1402                        Vandalism   
...                ...           ...                              ...   
327337      I152049637           802                   Simple Assault   
327338      I152049635          3831  Motor Vehicle Accident Response   
327339      I152049634          1842                   Drug Violation   
327340      I152049634          3125                  Warrant Arrests   
327308      I152049683           522             Residential Burglary   

                          OFFENSE_DESCRIPTION  DISTRICT REPORTING_AREA  \
0                        DISTURBING THE PEACE         2            495   
166                      M/V ACCIDENT - OTHER         6            783   
146                       TOWED MOTOR VEHICLE         3            237   
148                                 VANDALISM         8            344   
149                                 VANDALISM         8            368   
...                                       ...       ...            ...   
327337               ASSAULT SIMPLE - BATTERY         8            817   
327338  M/V - LEAVING SCENE - PROPERTY DAMAGE         3            602   
327339   DRUGS - POSS CLASS A - HEROIN, ETC.          7            569   
327340                         WARRANT ARREST         7            569   
327308      BURGLARY - RESIDENTIAL - NO FORCE         4            686   

       SHOOTING  YEAR  MONTH  DAY_OF_WEEK  ...  OCCURRED_DAY Summer  \
0             0  2018     10            6  ...    2018-10-03      0   
166           0  2018     10            6  ...    2018-10-03      0   
146           0  2018     10            6  ...    2018-10-03      0   
148           0  2018     10            6  ...    2018-10-03      0   
149           0  2018     10            6  ...    2018-10-03      0   
...         ...   ...    ...          ...  ...           ...    ...   
327337        0  2015      6            3  ...    2015-06-15      1   
327338        0  2015      6            3  ...    2015-06-15      1   
327339        0  2015      6            3  ...    2015-06-15      1   
327340        0  2015      6            3  ...    2015-06-15      1   
327308        0  2015      6            3  ...    2015-06-15      1   

        HOUR_12_16_17_18_19  HOUR_3_4_5_6 RIVER | CENTRE RA  UCR_Other  \
0                         0             0              1  1          0   
166                       0             0              1  1          0   
146                       0             0              1  1          0   
148                       1             0              1  1          0   
149                       0             0              1  1          0   
...                     ...           ...            ... ..        ...   
327337                    0             0              1  1          0   
327338                    0             0              1  1          0   
327339                    0             0              1  1          0   
327340                    0             0              1  1          0   
327308                    1             0              1  1          0   

        UCR_Part One  UCR_Part Three  UCR_Part Two  
0                  0               0             1  
166                0               1             0  
146                0               1             0  
148                0               0             1  
149                0               0             1  
...              ...             ...           ...  
327337             0               0             1  
327338             0               1             0  
327339             0  

In [78]:
from sklearn.preprocessing import StandardScaler

In [79]:
#train set split with the rate of 0.8 from sorted dataset and selecting specific features for my model
train_set = df_m_1[['Lat','Long','MONTH','HOUR', 'DISTRICT','UCR_Part One']].head((int(len(df_m_1))-(int(len(df_m_1) *0.8))))
train_set

Lat       Long  MONTH  HOUR  DISTRICT  UCR_Part One
0      42.262608 -71.121186     10    20         2             0
166    42.348886 -71.140074     10    11         6             0
146    42.319860 -71.064341     10    11         3             0
148    42.300308 -71.072064     10    12         8             0
149    42.293836 -71.051574     10     7         8             0
...          ...        ...    ...   ...       ...           ...
66575  42.380208 -71.034936      2     4        10             0
66576  42.293440 -71.047585      2     4         8             0
66577  42.352757 -71.082402      2     3         9             1
66578  42.300202 -71.078354      2     3         1             0
66579  42.294516 -71.058754      2     2         8             0

[61109 rows x 6 columns]

### train and validation set control for independency

In [80]:
index_control_train =train_set.reset_index()
index_control_train

index        Lat       Long  MONTH  HOUR  DISTRICT  UCR_Part One
0          0  42.262608 -71.121186     10    20         2             0
1        166  42.348886 -71.140074     10    11         6             0
2        146  42.319860 -71.064341     10    11         3             0
3        148  42.300308 -71.072064     10    12         8             0
4        149  42.293836 -71.051574     10     7         8             0
...      ...        ...        ...    ...   ...       ...           ...
61104  66575  42.380208 -71.034936      2     4        10             0
61105  66576  42.293440 -71.047585      2     4         8             0
61106  66577  42.352757 -71.082402      2     3         9             1
61107  66578  42.300202 -71.078354      2     3         1             0
61108  66579  42.294516 -71.058754      2     2         8             0

[61109 rows x 7 columns]

In [81]:
liste1 =[]

for x in index_control_train['index']:
    liste1.append(x)

liste1
    

[0,
 166,
 146,
 148,
 149,
 153,
 154,
 155,
 156,
 157,
 158,
 161,
 165,
 167,
 182,
 168,
 170,
 171,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 145,
 144,
 143,
 142,
 114,
 115,
 116,
 117,
 119,
 120,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 137,
 138,
 139,
 140,
 141,
 181,
 183,
 112,
 242,
 224,
 225,
 226,
 230,
 231,
 232,
 236,
 238,
 239,
 240,
 241,
 243,
 184,
 244,
 245,
 246,
 249,
 252,
 253,
 254,
 255,
 257,
 258,
 259,
 222,
 221,
 217,
 215,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 196,
 197,
 198,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 209,
 210,
 211,
 212,
 213,
 214,
 113,
 163,
 111,
 50,
 53,
 22,
 21,
 54,
 58,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 19,
 68,
 18,
 16,
 14,
 51,
 73,
 29,
 30,
 31,
 32,
 33,
 34,
 27,
 36,
 38,
 39,
 40,
 41,
 42,
 24,
 45,
 23,
 47,
 13,
 17,
 12,
 7,
 104,
 103,
 2,
 8,
 102,
 91,
 98,
 101,
 4,
 100,
 3,
 95,
 96,
 97,
 86,
 85,
 107,
 74,
 75,
 76,
 77,
 78,
 108,
 79,
 10,
 81,
 106,

In [82]:
#validation set split with the rate of 0.2 from sorted dataset and selecting specific features for my model
validation_set = df_m_1.tail(int(len(df_m_1) *0.2))[['Lat','Long','MONTH','HOUR','DISTRICT','UCR_Part One']]
groundTruth= validation_set['UCR_Part One'].to_frame()
validation_set= validation_set.drop('UCR_Part One', axis=1)
validation_set


Lat       Long  MONTH  HOUR  DISTRICT
264396  42.305407 -71.065471      2    12         8
264394  42.321045 -71.092820      2    13         3
264393  42.362403 -71.069547      2    13        11
264485  42.319047 -71.094000      2     5         3
264174  42.297690 -71.060910      2    19         8
...           ...        ...    ...   ...       ...
327337  42.288638 -71.066316      6    15         8
327338  42.333669 -71.103335      6    14         3
327339  42.304816 -71.109118      6    15         7
327340  42.304816 -71.109118      6    15         7
327308  42.283113 -71.143922      6    17         4

[61108 rows x 5 columns]

In [83]:
index_control_valid = validation_set.reset_index()
index_control_valid

index        Lat       Long  MONTH  HOUR  DISTRICT
0      264396  42.305407 -71.065471      2    12         8
1      264394  42.321045 -71.092820      2    13         3
2      264393  42.362403 -71.069547      2    13        11
3      264485  42.319047 -71.094000      2     5         3
4      264174  42.297690 -71.060910      2    19         8
...       ...        ...        ...    ...   ...       ...
61103  327337  42.288638 -71.066316      6    15         8
61104  327338  42.333669 -71.103335      6    14         3
61105  327339  42.304816 -71.109118      6    15         7
61106  327340  42.304816 -71.109118      6    15         7
61107  327308  42.283113 -71.143922      6    17         4

[61108 rows x 6 columns]

In [84]:
liste2 =[]

for y in index_control_valid['index']:
    liste2.append(y)
liste2
    

[264396,
 264394,
 264393,
 264485,
 264174,
 270065,
 263027,
 262707,
 263569,
 261007,
 261008,
 270066,
 262778,
 259166,
 263007,
 262549,
 260850,
 222856,
 222855,
 263946,
 263945,
 264553,
 264560,
 264561,
 264562,
 264558,
 264557,
 264563,
 264556,
 264753,
 264546,
 264552,
 264551,
 264550,
 264549,
 264565,
 264545,
 264544,
 264543,
 264542,
 264541,
 264539,
 264564,
 264571,
 264566,
 264580,
 264593,
 264592,
 264591,
 264589,
 264588,
 264587,
 264585,
 264584,
 264583,
 264582,
 264581,
 264579,
 264567,
 264578,
 264577,
 264576,
 264575,
 264574,
 264573,
 264572,
 264537,
 264570,
 264569,
 264568,
 264538,
 264530,
 264536,
 264459,
 264503,
 264495,
 264494,
 264492,
 264487,
 264482,
 264479,
 264475,
 264474,
 264469,
 262206,
 264444,
 264535,
 264443,
 261596,
 264429,
 264425,
 264408,
 264406,
 264395,
 261510,
 264377,
 264372,
 252442,
 264505,
 264506,
 264508,
 264509,
 264533,
 264532,
 264531,
 264597,
 264529,
 264528,
 264527,
 264526,
 264525,
 

### checking the independency between train and validation set

In [85]:
set(liste1)&set(liste2)

set()

In [86]:
groundTruth

UCR_Part One
264396             0
264394             0
264393             0
264485             0
264174             0
...              ...
327337             0
327338             0
327339             0
327340             0
327308             1

[61108 rows x 1 columns]

In [87]:
## scaling try for the model
# scaler = StandardScaler()
# scaled_validation_set = scaler.fit_transform(validation_set)
# scaled_validation_set = pd.DataFrame(data=scaled_validation_set, columns=['Summer','HOUR_12_16_17_18_19','DIS_A7','DIS_B2','DIS_B3', 'DIS_C11', 'DIS_C6', 'DIS_D14', 'DIS_D4', 'DIS_E13', 'DIS_E18', 'DIS_E5', 'UCR_Part One'])
# scaled_validation_set = scaled_validation_set.drop('UCR_Part One', axis=1)
# scaled_validation_set

In [88]:
#import necessary libraries for machine learning models
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import BernoulliNB
from sklearn.tree import ExtraTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.semi_supervised import LabelSpreading
from sklearn.svm import LinearSVC
from sklearn.neighbors.nearest_centroid import NearestCentroid
from sklearn.ensemble import RandomForestClassifier
from lightgbm import LGBMClassifier

In [89]:
# defining function for getting the classification metrics easily
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

def classification_metrics(y_test, predict):
    print("Confusion Matrix:\n")
    print(confusion_matrix(y_test, predict))
    print("\nAccuracy: ", accuracy_score(y_test, predict))
    print("\nClassification report:\n")
    print(classification_report(y_test, predict))

In [90]:
train_set

Lat       Long  MONTH  HOUR  DISTRICT  UCR_Part One
0      42.262608 -71.121186     10    20         2             0
166    42.348886 -71.140074     10    11         6             0
146    42.319860 -71.064341     10    11         3             0
148    42.300308 -71.072064     10    12         8             0
149    42.293836 -71.051574     10     7         8             0
...          ...        ...    ...   ...       ...           ...
66575  42.380208 -71.034936      2     4        10             0
66576  42.293440 -71.047585      2     4         8             0
66577  42.352757 -71.082402      2     3         9             1
66578  42.300202 -71.078354      2     3         1             0
66579  42.294516 -71.058754      2     2         8             0

[61109 rows x 6 columns]

In [91]:
# scaler = StandardScaler()
# train_scaled = scaler.fit_transform(train_set)
# train_scaled = pd.DataFrame(data=train_scaled, columns=['Summer','HOUR_12_16_17_18_19','DIS_A7','DIS_B2','DIS_B3', 'DIS_C11', 'DIS_C6', 'DIS_D14', 'DIS_D4', 'DIS_E13', 'DIS_E18', 'DIS_E5', 'UCR_Part One'])
# train_scaled

In [92]:
# train and test split from train_set (0.8) 
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(train_set.drop(columns=["UCR_Part One"]), train_set["UCR_Part One"], random_state = 0, test_size = 0.3, train_size=0.7)  

In [93]:
x_train

Lat       Long  MONTH  HOUR  DISTRICT
51816  42.318759 -71.102122      4    10         7
17123  42.317147 -71.113298      7     7         7
28867  42.296662 -71.061218      6    10         8
55858  42.348357 -71.136453      3    17         6
26759  42.323391 -71.095475      6     7         3
...          ...        ...    ...   ...       ...
50089  42.284826 -71.091374      4    21         1
57195  42.369081 -71.040216      3     8        10
46505  42.378649 -71.059513      4    11        12
47497  42.314688 -71.098435      4    15         7
3151   42.358427 -71.068900      9    13        11

[42776 rows x 5 columns]

In [94]:
y_train

51816    0
17123    0
28867    1
55858    0
26759    0
        ..
50089    0
57195    0
46505    0
47497    0
3151     0
Name: UCR_Part One, Length: 42776, dtype: uint8

In [95]:
x_train

Lat       Long  MONTH  HOUR  DISTRICT
51816  42.318759 -71.102122      4    10         7
17123  42.317147 -71.113298      7     7         7
28867  42.296662 -71.061218      6    10         8
55858  42.348357 -71.136453      3    17         6
26759  42.323391 -71.095475      6     7         3
...          ...        ...    ...   ...       ...
50089  42.284826 -71.091374      4    21         1
57195  42.369081 -71.040216      3     8        10
46505  42.378649 -71.059513      4    11        12
47497  42.314688 -71.098435      4    15         7
3151   42.358427 -71.068900      9    13        11

[42776 rows x 5 columns]

### Decision Tree

In [96]:
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier(random_state=0)
dtc.fit(x_train, y_train)
predict = pd.DataFrame(data=dtc.predict(x_test))
classification_metrics(y_test, predict)

Confusion Matrix:

[[12494  2401]
 [ 2523   915]]

Accuracy:  0.7314132984236077

Classification report:

              precision    recall  f1-score   support

           0       0.83      0.84      0.84     14895
           1       0.28      0.27      0.27      3438

    accuracy                           0.73     18333
   macro avg       0.55      0.55      0.55     18333
weighted avg       0.73      0.73      0.73     18333



### Decision Tree Validation Test Score

In [97]:
predict = pd.DataFrame(data=dtc.predict(validation_set))
dtc_accuracy = classification_metrics(groundTruth, predict)
print('dtc_accuracy:', dtc_accuracy)

Confusion Matrix:

[[38054  9232]
 [10332  3490]]

Accuracy:  0.6798455194082608

Classification report:

              precision    recall  f1-score   support

           0       0.79      0.80      0.80     47286
           1       0.27      0.25      0.26     13822

    accuracy                           0.68     61108
   macro avg       0.53      0.53      0.53     61108
weighted avg       0.67      0.68      0.68     61108

dtc_accuracy: None


### Random Forest

In [98]:
from sklearn.ensemble import RandomForestClassifier
rfC = RandomForestClassifier(max_depth= 8, max_leaf_nodes=5, min_samples_leaf=5, n_estimators= 10, random_state=0, max_features='log2', class_weight = 'balanced')

rfC.fit(x_train, y_train)
predict = pd.DataFrame(data=rfC.predict(x_test))
classification_metrics(y_test, predict)

Confusion Matrix:

[[11200  3695]
 [ 2134  1304]]

Accuracy:  0.6820487645229913

Classification report:

              precision    recall  f1-score   support

           0       0.84      0.75      0.79     14895
           1       0.26      0.38      0.31      3438

    accuracy                           0.68     18333
   macro avg       0.55      0.57      0.55     18333
weighted avg       0.73      0.68      0.70     18333



In [99]:
validation_set

Lat       Long  MONTH  HOUR  DISTRICT
264396  42.305407 -71.065471      2    12         8
264394  42.321045 -71.092820      2    13         3
264393  42.362403 -71.069547      2    13        11
264485  42.319047 -71.094000      2     5         3
264174  42.297690 -71.060910      2    19         8
...           ...        ...    ...   ...       ...
327337  42.288638 -71.066316      6    15         8
327338  42.333669 -71.103335      6    14         3
327339  42.304816 -71.109118      6    15         7
327340  42.304816 -71.109118      6    15         7
327308  42.283113 -71.143922      6    17         4

[61108 rows x 5 columns]

### Random Forest Validation Test Score

In [100]:
predict = pd.DataFrame(data=rfC.predict(validation_set))
rfC_accuracy = classification_metrics(groundTruth, predict)
print('rfC_accuracy:', rfC_accuracy)

Confusion Matrix:

[[33647 13639]
 [ 8333  5489]]

Accuracy:  0.6404398769391896

Classification report:

              precision    recall  f1-score   support

           0       0.80      0.71      0.75     47286
           1       0.29      0.40      0.33     13822

    accuracy                           0.64     61108
   macro avg       0.54      0.55      0.54     61108
weighted avg       0.69      0.64      0.66     61108

rfC_accuracy: None


In [101]:
from sklearn.model_selection import GridSearchCV

### ExtraTree Classifier 

In [102]:
from sklearn.ensemble import ExtraTreesClassifier
etC = ExtraTreesClassifier(random_state=0, n_estimators=50)

etC.fit(x_train, y_train)
predict = pd.DataFrame(data=etC.predict(x_test))
classification_metrics(y_test, predict)

Confusion Matrix:

[[13806  1089]
 [ 2937   501]]

Accuracy:  0.7803960072001309

Classification report:

              precision    recall  f1-score   support

           0       0.82      0.93      0.87     14895
           1       0.32      0.15      0.20      3438

    accuracy                           0.78     18333
   macro avg       0.57      0.54      0.54     18333
weighted avg       0.73      0.78      0.75     18333



### ExtraTree Classifier Validation Test Score

In [103]:
predict = pd.DataFrame(data=etC.predict(validation_set))
etC_accuracy = classification_metrics(groundTruth, predict)
print('etC_accuracy:', etC_accuracy)

Confusion Matrix:

[[44451  2835]
 [12400  1422]]

Accuracy:  0.7506873077174838

Classification report:

              precision    recall  f1-score   support

           0       0.78      0.94      0.85     47286
           1       0.33      0.10      0.16     13822

    accuracy                           0.75     61108
   macro avg       0.56      0.52      0.51     61108
weighted avg       0.68      0.75      0.70     61108

etC_accuracy: None


### Ada Boosting

In [104]:
from sklearn.ensemble import AdaBoostClassifier

abC = AdaBoostClassifier(random_state=0, n_estimators=10, learning_rate=0.9)
abC.fit(x_train, y_train)
predict = pd.DataFrame(data=abC.predict(x_test), index = x_test.index)
classification_metrics(y_test, predict)



Confusion Matrix:

[[14895     0]
 [ 3438     0]]

Accuracy:  0.8124693176239568

Classification report:

              precision    recall  f1-score   support

           0       0.81      1.00      0.90     14895
           1       0.00      0.00      0.00      3438

    accuracy                           0.81     18333
   macro avg       0.41      0.50      0.45     18333
weighted avg       0.66      0.81      0.73     18333



/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Ada Boosting Validation Test Score

In [105]:
predict = pd.DataFrame(data=abC.predict(validation_set))
abC_accuracy = accuracy_score(groundTruth, predict)
print('abC_accuracy:', abC_accuracy)

abC_accuracy: 0.7738103030699744


### Gradient Boosting

In [106]:
from sklearn.ensemble import GradientBoostingClassifier

gbC = GradientBoostingClassifier(random_state=0, n_estimators=10)
gbC.fit(x_train, y_train)
predict = pd.DataFrame(data=gbC.predict(x_test), index = x_test.index)
classification_metrics(y_test, predict)


Confusion Matrix:

[[14895     0]
 [ 3438     0]]

Accuracy:  0.8124693176239568

Classification report:

              precision    recall  f1-score   support

           0       0.81      1.00      0.90     14895
           1       0.00      0.00      0.00      3438

    accuracy                           0.81     18333
   macro avg       0.41      0.50      0.45     18333
weighted avg       0.66      0.81      0.73     18333



/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Gradient Boosting Validation Test Score

In [107]:
predict = pd.DataFrame(data=gbC.predict(validation_set))
gbC_accuracy = classification_metrics(groundTruth, predict)
print('gbC_accuracy:', gbC_accuracy)


Confusion Matrix:

[[47286     0]
 [13822     0]]

Accuracy:  0.7738103030699744

Classification report:

              precision    recall  f1-score   support

           0       0.77      1.00      0.87     47286
           1       0.00      0.00      0.00     13822

    accuracy                           0.77     61108
   macro avg       0.39      0.50      0.44     61108
weighted avg       0.60      0.77      0.68     61108

gbC_accuracy: None


/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### XGBoost

In [120]:
from xgboost import XGBClassifier

xgB = XGBClassifier(scale_pos_weight=5.2,random_state=0)
xgB.fit(x_train, y_train)
predict = pd.DataFrame(data=xgB.predict(x_test))
classification_metrics(y_test, predict)

Confusion Matrix:

[[9074 5821]
 [1396 2042]]

Accuracy:  0.6063382970599466

Classification report:

              precision    recall  f1-score   support

           0       0.87      0.61      0.72     14895
           1       0.26      0.59      0.36      3438

    accuracy                           0.61     18333
   macro avg       0.56      0.60      0.54     18333
weighted avg       0.75      0.61      0.65     18333



### XGBoost Validation Test Score

In [121]:
predict = pd.DataFrame(data=xgB.predict(validation_set))
xgB_accuracy = classification_metrics(groundTruth, predict)
print('xgB_accuracy:', xgB_accuracy)

Confusion Matrix:

[[28604 18682]
 [ 6439  7383]]

Accuracy:  0.5889081625973686

Classification report:

              precision    recall  f1-score   support

           0       0.82      0.60      0.69     47286
           1       0.28      0.53      0.37     13822

    accuracy                           0.59     61108
   macro avg       0.55      0.57      0.53     61108
weighted avg       0.70      0.59      0.62     61108

xgB_accuracy: None


### Logistic Regression

In [110]:
from sklearn.linear_model import LogisticRegression

lrC = LogisticRegression(max_iter=10000, random_state=0)
lrC.fit(x_train, y_train)
predict = pd.DataFrame(data=lrC.predict(x_test))
classification_metrics(y_test, predict)

Confusion Matrix:

[[14895     0]
 [ 3438     0]]

Accuracy:  0.8124693176239568

Classification report:

              precision    recall  f1-score   support

           0       0.81      1.00      0.90     14895
           1       0.00      0.00      0.00      3438

    accuracy                           0.81     18333
   macro avg       0.41      0.50      0.45     18333
weighted avg       0.66      0.81      0.73     18333



/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Logistic Regression Validation Test Score

In [111]:
predict = pd.DataFrame(data=lrC.predict(validation_set))
lrC_accuracy = accuracy_score(groundTruth, predict)
print('lrC_accuracy:', lrC_accuracy)

lrC_accuracy: 0.7738103030699744


### KNeighbors Classifier

In [112]:
# knC = KNeighborsClassifier()
# knC.fit(x_train, y_train) 
# knC_pred = knC.predict(x_test)

# classification_metrics(y_test, knC_pred)


### KNeigbors Classifier Validation Test Score

In [113]:
# predict = pd.DataFrame(data=knC.predict(scaled_validation_set))
# knC_accuracy = accuracy_score(groundTruth, predict)
# print('knC_accuracy:', knC_accuracy)

### LGBM Classifier

In [122]:
lgbm = LGBMClassifier(scale_pos_weight=4.7, random_state=0)
lgbm.fit(x_train, y_train)
lgbm_pred = lgbm.predict(x_test)

classification_metrics(y_test, lgbm_pred)

Confusion Matrix:

[[8637 6258]
 [1293 2145]]

Accuracy:  0.5881197839960727

Classification report:

              precision    recall  f1-score   support

           0       0.87      0.58      0.70     14895
           1       0.26      0.62      0.36      3438

    accuracy                           0.59     18333
   macro avg       0.56      0.60      0.53     18333
weighted avg       0.75      0.59      0.63     18333



### LGBM Classifier Validation Test Score

In [115]:
predict = pd.DataFrame(data=lgbm.predict(validation_set))
lgbm_accuracy = classification_metrics(groundTruth, predict)
print('lgbm_accuracy:', lgbm_accuracy)

Confusion Matrix:

[[30194 17092]
 [ 6692  7130]]

Accuracy:  0.6107874582706029

Classification report:

              precision    recall  f1-score   support

           0       0.82      0.64      0.72     47286
           1       0.29      0.52      0.37     13822

    accuracy                           0.61     61108
   macro avg       0.56      0.58      0.55     61108
weighted avg       0.70      0.61      0.64     61108

lgbm_accuracy: None


### Gaussian 

In [116]:
gauss = GaussianNB()
gauss = gauss.fit(x_train, y_train)
gauss_pred = gauss.predict(x_test)

classification_metrics(y_test, gauss_pred)

Confusion Matrix:

[[14895     0]
 [ 3438     0]]

Accuracy:  0.8124693176239568

Classification report:

              precision    recall  f1-score   support

           0       0.81      1.00      0.90     14895
           1       0.00      0.00      0.00      3438

    accuracy                           0.81     18333
   macro avg       0.41      0.50      0.45     18333
weighted avg       0.66      0.81      0.73     18333



/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Gaussian Validation Test Score

In [117]:
predict = pd.DataFrame(data=gauss.predict(validation_set))
gauss_accuracy = classification_metrics(groundTruth, predict)
    
print('gauss_accuracy:', gauss_accuracy)

Confusion Matrix:

[[47286     0]
 [13822     0]]

Accuracy:  0.7738103030699744

Classification report:

              precision    recall  f1-score   support

           0       0.77      1.00      0.87     47286
           1       0.00      0.00      0.00     13822

    accuracy                           0.77     61108
   macro avg       0.39      0.50      0.44     61108
weighted avg       0.60      0.77      0.68     61108

gauss_accuracy: None


/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
