In [1]:
#importing the necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno

In [2]:
#reading csv file from db
df = pd.read_csv('../input/boston-crime-data/crime.csv', encoding='latin-1')
df.head()

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


INCIDENT_NUMBER  OFFENSE_CODE  OFFENSE_CODE_GROUP  \
0      I182080058          2403  Disorderly Conduct   
1      I182080053          3201       Property Lost   
2      I182080052          2647               Other   
3      I182080051           413  Aggravated Assault   
4      I182080050          3122            Aircraft   

              OFFENSE_DESCRIPTION DISTRICT REPORTING_AREA SHOOTING  \
0            DISTURBING THE PEACE      E18            495      NaN   
1                 PROPERTY - LOST      D14            795      NaN   
2       THREATS TO DO BODILY HARM       B2            329      NaN   
3  ASSAULT - AGGRAVATED - BATTERY       A1             92      NaN   
4              AIRCRAFT INCIDENTS       A7             36      NaN   

      OCCURRED_ON_DATE  YEAR  MONTH DAY_OF_WEEK  HOUR    UCR_PART  \
0  2018-10-03 20:13:00  2018     10   Wednesday    20    Part Two   
1  2018-08-30 20:00:00  2018      8    Thursday    20  Part Three   
2  2018-10-03 19:20:00  2018     10   Wednesday    19    Part Two   
3  2018-10-03 20:00:00  2018     10   Wednesday    20    Part One   
4  2018-10-03 20:49:00  2018     10   Wednesday    20  Part Three   

         STREET        Lat       Long                     Location  
0  ARLINGTON ST  42.262608 -71.121186  (42.26260773, -71.12118637)  
1    ALLSTON ST  42.352111 -71.135311  (42.35211146, -71.13531147)  
2      DEVON ST  42.308126 -71.076930  (42.30812619, -71.07692974)  
3  CAMBRIDGE ST  42.359454 -71.059648  (42.35945371, -71.05964817)  
4   PRESCOTT ST  42.375258 -71.024663  (42.37525782, -71.02466343)

# Feature Engineering

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 327820 entries, 0 to 327819
Data columns (total 17 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   INCIDENT_NUMBER      327820 non-null  object 
 1   OFFENSE_CODE         327820 non-null  int64  
 2   OFFENSE_CODE_GROUP   327820 non-null  object 
 3   OFFENSE_DESCRIPTION  327820 non-null  object 
 4   DISTRICT             326046 non-null  object 
 5   REPORTING_AREA       327820 non-null  object 
 6   SHOOTING             1055 non-null    object 
 7   OCCURRED_ON_DATE     327820 non-null  object 
 8   YEAR                 327820 non-null  int64  
 9   MONTH                327820 non-null  int64  
 10  DAY_OF_WEEK          327820 non-null  object 
 11  HOUR                 327820 non-null  int64  
 12  UCR_PART             327727 non-null  object 
 13  STREET               316843 non-null  object 
 14  Lat                  307188 non-null  float64
 15  Long             

In [4]:
#filling null values in shooting feature as '0' and replacing 'Y' values with '1'
df['SHOOTING']= df['SHOOTING'].fillna(value='0')
df['SHOOTING'] = df['SHOOTING'].replace('Y',1)
df

INCIDENT_NUMBER  OFFENSE_CODE  OFFENSE_CODE_GROUP  \
0           I182080058          2403  Disorderly Conduct   
1           I182080053          3201       Property Lost   
2           I182080052          2647               Other   
3           I182080051           413  Aggravated Assault   
4           I182080050          3122            Aircraft   
...                ...           ...                 ...   
327815   I050310906-00          3125     Warrant Arrests   
327816   I030217815-08           111            Homicide   
327817   I030217815-08          3125     Warrant Arrests   
327818   I010370257-00          3125     Warrant Arrests   
327819       142052550          3125     Warrant Arrests   

                        OFFENSE_DESCRIPTION DISTRICT REPORTING_AREA SHOOTING  \
0                      DISTURBING THE PEACE      E18            495        0   
1                           PROPERTY - LOST      D14            795        0   
2                 THREATS TO DO BODILY HARM       B2            329        0   
3            ASSAULT - AGGRAVATED - BATTERY       A1             92        0   
4                        AIRCRAFT INCIDENTS       A7             36        0   
...                                     ...      ...            ...      ...   
327815                       WARRANT ARREST       D4            285        0   
327816  MURDER, NON-NEGLIGIENT MANSLAUGHTER      E18            520        0   
327817                       WARRANT ARREST      E18            520        0   
327818                       WARRANT ARREST      E13            569        0   
327819                       WARRANT ARREST       D4            903        0   

           OCCURRED_ON_DATE  YEAR  MONTH DAY_OF_WEEK  HOUR    UCR_PART  \
0       2018-10-03 20:13:00  2018     10   Wednesday    20    Part Two   
1       2018-08-30 20:00:00  2018      8    Thursday    20  Part Three   
2       2018-10-03 19:20:00  2018     10   Wednesday    19    Part Two   
3       2018-10-03 20:00:00  2018     10   Wednesday    20    Part One   
4       2018-10-03 20:49:00  2018     10   Wednesday    20  Part Three   
...                     ...   ...    ...         ...   ...         ...   
327815  2016-06-05 17:25:00  2016      6      Sunday    17  Part Three   
327816  2015-07-09 13:38:00  2015      7    Thursday    13    Part One   
327817  2015-07-09 13:38:00  2015      7    Thursday    13  Part Three   
327818  2016-05-31 19:35:00  2016      5     Tuesday    19  Part Three   
327819  2015-06-22 00:12:00  2015      6      Monday     0  Part Three   

                   STREET        Lat       Long                     Location  
0            ARLINGTON ST  42.262608 -71.121186  (42.26260773, -71.12118637)  
1              ALLSTON ST  42.352111 -71.135311  (42.35211146, -71.13531147)  
2                DEVON ST  42.308126 -71.076930  (42.30812619, -71.07692974)  
3            CAMBRIDGE ST  42.359454 -71.059648  (42.35945371, -71.05964817)  
4             PRESCOTT ST  42.375258 -71.024663  (42.37525782, -71.02466343)  
...                   ...        ...        ...                          ...  
327815        COVENTRY ST  42.336951 -71.085748  (42.33695098, -71.08574813)  
327816           RIVER ST  42.255926 -71.123172  (42.25592648, -71.12317207)  
327817           RIVER ST  42.255926 -71.123172  (42.25592648, -71.12317207)  
327818  NEW WASHINGTON ST  42.302333 -71.111565  (42.30233307, -71.11156487)  
327819      WASHINGTON ST  42.333839 -71.080290  (42.33383935, -71.08029038)  

[327820 rows x 17 columns]

In [5]:
#droping Nan values from Lat and Long 
#droping from Lat and Long with the values of '-1' --removing outliers
# it reduced the number of rows from 327.727 to 306.320
df = df.dropna(subset = ['Lat', 'Long'])
df = df[df['Lat'] > 0]
df

INCIDENT_NUMBER  OFFENSE_CODE  OFFENSE_CODE_GROUP  \
0           I182080058          2403  Disorderly Conduct   
1           I182080053          3201       Property Lost   
2           I182080052          2647               Other   
3           I182080051           413  Aggravated Assault   
4           I182080050          3122            Aircraft   
...                ...           ...                 ...   
327815   I050310906-00          3125     Warrant Arrests   
327816   I030217815-08           111            Homicide   
327817   I030217815-08          3125     Warrant Arrests   
327818   I010370257-00          3125     Warrant Arrests   
327819       142052550          3125     Warrant Arrests   

                        OFFENSE_DESCRIPTION DISTRICT REPORTING_AREA SHOOTING  \
0                      DISTURBING THE PEACE      E18            495        0   
1                           PROPERTY - LOST      D14            795        0   
2                 THREATS TO DO BODILY HARM       B2            329        0   
3            ASSAULT - AGGRAVATED - BATTERY       A1             92        0   
4                        AIRCRAFT INCIDENTS       A7             36        0   
...                                     ...      ...            ...      ...   
327815                       WARRANT ARREST       D4            285        0   
327816  MURDER, NON-NEGLIGIENT MANSLAUGHTER      E18            520        0   
327817                       WARRANT ARREST      E18            520        0   
327818                       WARRANT ARREST      E13            569        0   
327819                       WARRANT ARREST       D4            903        0   

           OCCURRED_ON_DATE  YEAR  MONTH DAY_OF_WEEK  HOUR    UCR_PART  \
0       2018-10-03 20:13:00  2018     10   Wednesday    20    Part Two   
1       2018-08-30 20:00:00  2018      8    Thursday    20  Part Three   
2       2018-10-03 19:20:00  2018     10   Wednesday    19    Part Two   
3       2018-10-03 20:00:00  2018     10   Wednesday    20    Part One   
4       2018-10-03 20:49:00  2018     10   Wednesday    20  Part Three   
...                     ...   ...    ...         ...   ...         ...   
327815  2016-06-05 17:25:00  2016      6      Sunday    17  Part Three   
327816  2015-07-09 13:38:00  2015      7    Thursday    13    Part One   
327817  2015-07-09 13:38:00  2015      7    Thursday    13  Part Three   
327818  2016-05-31 19:35:00  2016      5     Tuesday    19  Part Three   
327819  2015-06-22 00:12:00  2015      6      Monday     0  Part Three   

                   STREET        Lat       Long                     Location  
0            ARLINGTON ST  42.262608 -71.121186  (42.26260773, -71.12118637)  
1              ALLSTON ST  42.352111 -71.135311  (42.35211146, -71.13531147)  
2                DEVON ST  42.308126 -71.076930  (42.30812619, -71.07692974)  
3            CAMBRIDGE ST  42.359454 -71.059648  (42.35945371, -71.05964817)  
4             PRESCOTT ST  42.375258 -71.024663  (42.37525782, -71.02466343)  
...                   ...        ...        ...                          ...  
327815        COVENTRY ST  42.336951 -71.085748  (42.33695098, -71.08574813)  
327816           RIVER ST  42.255926 -71.123172  (42.25592648, -71.12317207)  
327817           RIVER ST  42.255926 -71.123172  (42.25592648, -71.12317207)  
327818  NEW WASHINGTON ST  42.302333 -71.111565  (42.30233307, -71.11156487)  
327819      WASHINGTON ST  42.333839 -71.080290  (42.33383935, -71.08029038)  

[306413 rows x 17 columns]

In [6]:
df.describe()

OFFENSE_CODE           YEAR          MONTH           HOUR  \
count  306413.000000  306413.000000  306413.000000  306413.000000   
mean     2296.613835    2016.591248       6.674469      13.122717   
std      1182.763063       1.013933       3.258638       6.277278   
min       111.000000    2015.000000       1.000000       0.000000   
25%       802.000000    2016.000000       4.000000       9.000000   
50%      2907.000000    2017.000000       7.000000      14.000000   
75%      3201.000000    2017.000000       9.000000      18.000000   
max      3831.000000    2018.000000      12.000000      23.000000   

                 Lat           Long  
count  306413.000000  306413.000000  
mean       42.322292     -71.082841  
std         0.031859       0.029744  
min        42.232413     -71.178674  
25%        42.297555     -71.097189  
50%        42.325646     -71.077550  
75%        42.348624     -71.062563  
max        42.395042     -70.963676

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 306413 entries, 0 to 327819
Data columns (total 17 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   INCIDENT_NUMBER      306413 non-null  object 
 1   OFFENSE_CODE         306413 non-null  int64  
 2   OFFENSE_CODE_GROUP   306413 non-null  object 
 3   OFFENSE_DESCRIPTION  306413 non-null  object 
 4   DISTRICT             305542 non-null  object 
 5   REPORTING_AREA       306413 non-null  object 
 6   SHOOTING             306413 non-null  object 
 7   OCCURRED_ON_DATE     306413 non-null  object 
 8   YEAR                 306413 non-null  int64  
 9   MONTH                306413 non-null  int64  
 10  DAY_OF_WEEK          306413 non-null  object 
 11  HOUR                 306413 non-null  int64  
 12  UCR_PART             306320 non-null  object 
 13  STREET               304631 non-null  object 
 14  Lat                  306413 non-null  float64
 15  Long             

In [8]:
df["OCCURRED_ON_DATE"]=pd.to_datetime(df["OCCURRED_ON_DATE"],infer_datetime_format=True)
df["OCCURRED_DAY"]=df["OCCURRED_ON_DATE"].apply(lambda x: x.date())
df = df.drop(['OCCURRED_ON_DATE'],axis = 1)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 306413 entries, 0 to 327819
Data columns (total 17 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   INCIDENT_NUMBER      306413 non-null  object 
 1   OFFENSE_CODE         306413 non-null  int64  
 2   OFFENSE_CODE_GROUP   306413 non-null  object 
 3   OFFENSE_DESCRIPTION  306413 non-null  object 
 4   DISTRICT             305542 non-null  object 
 5   REPORTING_AREA       306413 non-null  object 
 6   SHOOTING             306413 non-null  object 
 7   YEAR                 306413 non-null  int64  
 8   MONTH                306413 non-null  int64  
 9   DAY_OF_WEEK          306413 non-null  object 
 10  HOUR                 306413 non-null  int64  
 11  UCR_PART             306320 non-null  object 
 12  STREET               304631 non-null  object 
 13  Lat                  306413 non-null  float64
 14  Long                 306413 non-null  float64
 15  Location         

In [9]:
df_m_1 = df.copy()
df_m_1 = df_m_1.sort_values(by =['OCCURRED_DAY'], ascending=False)
df_m_1['OCCURRED_DAY']= pd.to_datetime(df_m_1['OCCURRED_DAY'])
df_m_1

INCIDENT_NUMBER  OFFENSE_CODE               OFFENSE_CODE_GROUP  \
0           I182080058          2403               Disorderly Conduct   
166         I182079875          3801  Motor Vehicle Accident Response   
146         I182079895          3410                            Towed   
148         I182079893          1402                        Vandalism   
149         I182079892          1402                        Vandalism   
...                ...           ...                              ...   
327337      I152049637           802                   Simple Assault   
327338      I152049635          3831  Motor Vehicle Accident Response   
327339      I152049634          1842                   Drug Violation   
327340      I152049634          3125                  Warrant Arrests   
327308      I152049683           522             Residential Burglary   

                          OFFENSE_DESCRIPTION DISTRICT REPORTING_AREA  \
0                        DISTURBING THE PEACE      E18            495   
166                      M/V ACCIDENT - OTHER      D14            783   
146                       TOWED MOTOR VEHICLE       B2            237   
148                                 VANDALISM      C11            344   
149                                 VANDALISM      C11            368   
...                                       ...      ...            ...   
327337               ASSAULT SIMPLE - BATTERY      C11            817   
327338  M/V - LEAVING SCENE - PROPERTY DAMAGE       B2            602   
327339   DRUGS - POSS CLASS A - HEROIN, ETC.       E13            569   
327340                         WARRANT ARREST      E13            569   
327308      BURGLARY - RESIDENTIAL - NO FORCE       E5            686   

       SHOOTING  YEAR  MONTH DAY_OF_WEEK  HOUR    UCR_PART            STREET  \
0             0  2018     10   Wednesday    20    Part Two      ARLINGTON ST   
166           0  2018     10   Wednesday    11  Part Three  COMMONWEALTH AVE   
146           0  2018     10   Wednesday    11  Part Three        EASTMAN ST   
148           0  2018     10   Wednesday    12    Part Two        BOWDOIN ST   
149           0  2018     10   Wednesday     7    Part Two      NEPONSET AVE   
...         ...   ...    ...         ...   ...         ...               ...   
327337        0  2015      6      Monday    15    Part Two        TALBOT AVE   
327338        0  2015      6      Monday    14  Part Three        TREMONT ST   
327339        0  2015      6      Monday    15    Part Two       BROOKLEY RD   
327340        0  2015      6      Monday    15  Part Three       BROOKLEY RD   
327308        0  2015      6      Monday    17    Part One       COLBERG AVE   

              Lat       Long                     Location OCCURRED_DAY  
0       42.262608 -71.121186  (42.26260773, -71.12118637)   2018-10-03  
166     42.348886 -71.140074  (42.34888559, -71.14007361)   2018-10-03  
146     42.319860 -71.064341  (42.31986040, -71.06434120)   2018-10-03  
148     42.300308 -71.072064  (42.30030819, -71.07206425)   2018-10-03  
149     42.293836 -71.051574  (42.29383600, -71.05157448)   2018-10-03  
...           ...        ...                          ...          ...  
327337  42.288638 -71.066316  (42.28863812, -71.06631579)   2015-06-15  
327338  42.333669 -71.103335  (42.33366866, -71.10333486)   2015-06-15  
327339  42.304816 -71.109118  (42.30481623, -71.10911850)   2015-06-15  
327340  42.304816 -71.109118  (42.30481623, -71.10911850)   2015-06-15  
327308  42.283113 -71.143922  (42.28311294, -71.14392166)   2015-06-15  

[306413 rows x 17 columns]

In [10]:
df['DAY_OF_WEEK'].value_counts()

Friday       46494
Wednesday    45059
Thursday     44677
Tuesday      44517
Monday       43919
Saturday     42873
Sunday       38874
Name: DAY_OF_WEEK, dtype: int64

In [11]:
df_m_1['SHOOTING'] = df_m_1['SHOOTING'].astype('int')

In [12]:
df_m_1['DAY_OF_WEEK'] = df_m_1['DAY_OF_WEEK'].map({
    'Tuesday':4, 
    'Saturday':2, 
    'Monday':3, 
    'Sunday':1, 
    'Thursday':5, 
    'Wednesday':6,
    'Friday':7
})
df_m_1

INCIDENT_NUMBER  OFFENSE_CODE               OFFENSE_CODE_GROUP  \
0           I182080058          2403               Disorderly Conduct   
166         I182079875          3801  Motor Vehicle Accident Response   
146         I182079895          3410                            Towed   
148         I182079893          1402                        Vandalism   
149         I182079892          1402                        Vandalism   
...                ...           ...                              ...   
327337      I152049637           802                   Simple Assault   
327338      I152049635          3831  Motor Vehicle Accident Response   
327339      I152049634          1842                   Drug Violation   
327340      I152049634          3125                  Warrant Arrests   
327308      I152049683           522             Residential Burglary   

                          OFFENSE_DESCRIPTION DISTRICT REPORTING_AREA  \
0                        DISTURBING THE PEACE      E18            495   
166                      M/V ACCIDENT - OTHER      D14            783   
146                       TOWED MOTOR VEHICLE       B2            237   
148                                 VANDALISM      C11            344   
149                                 VANDALISM      C11            368   
...                                       ...      ...            ...   
327337               ASSAULT SIMPLE - BATTERY      C11            817   
327338  M/V - LEAVING SCENE - PROPERTY DAMAGE       B2            602   
327339   DRUGS - POSS CLASS A - HEROIN, ETC.       E13            569   
327340                         WARRANT ARREST      E13            569   
327308      BURGLARY - RESIDENTIAL - NO FORCE       E5            686   

        SHOOTING  YEAR  MONTH  DAY_OF_WEEK  HOUR    UCR_PART  \
0              0  2018     10            6    20    Part Two   
166            0  2018     10            6    11  Part Three   
146            0  2018     10            6    11  Part Three   
148            0  2018     10            6    12    Part Two   
149            0  2018     10            6     7    Part Two   
...          ...   ...    ...          ...   ...         ...   
327337         0  2015      6            3    15    Part Two   
327338         0  2015      6            3    14  Part Three   
327339         0  2015      6            3    15    Part Two   
327340         0  2015      6            3    15  Part Three   
327308         0  2015      6            3    17    Part One   

                  STREET        Lat       Long                     Location  \
0           ARLINGTON ST  42.262608 -71.121186  (42.26260773, -71.12118637)   
166     COMMONWEALTH AVE  42.348886 -71.140074  (42.34888559, -71.14007361)   
146           EASTMAN ST  42.319860 -71.064341  (42.31986040, -71.06434120)   
148           BOWDOIN ST  42.300308 -71.072064  (42.30030819, -71.07206425)   
149         NEPONSET AVE  42.293836 -71.051574  (42.29383600, -71.05157448)   
...                  ...        ...        ...                          ...   
327337        TALBOT AVE  42.288638 -71.066316  (42.28863812, -71.06631579)   
327338        TREMONT ST  42.333669 -71.103335  (42.33366866, -71.10333486)   
327339       BROOKLEY RD  42.304816 -71.109118  (42.30481623, -71.10911850)   
327340       BROOKLEY RD  42.304816 -71.109118  (42.30481623, -71.10911850)   
327308       COLBERG AVE  42.283113 -71.143922  (42.28311294, -71.14392166)   

       OCCURRED_DAY  
0        2018-10-03  
166      2018-10-03  
146      2018-10-03  
148      2018-10-03  
149      2018-10-03  
...             ...  
327337   2015-06-15  
327338   2015-06-15  
327339   2015-06-15  
327340   2015-06-15  
327308   2015-06-15  

[306413 rows x 17 columns]

In [13]:
# df_m_1['UCR_PART'] = df_m_1['UCR_PART'].map({
#     'Part One':3, 
#     'Part Two':2, 
#     'Part Three':1, 
#     'Other':0, 

# })
# df_m_1

In [14]:
df_m_1['Summer']=0
df_m_1['Summer']=df_m_1["MONTH"].apply(lambda x: 1 if x==6 or x==7 or x==8 or x==9 else 0)


df_m_1['HOUR_12_16_17_18']=0
df_m_1['HOUR_12_16_17_18']=df_m_1["HOUR"].apply(lambda x: 1 if x==12 or x==16 or x==17 or x==18 or x==19 else 0)
df_m_1


INCIDENT_NUMBER  OFFENSE_CODE               OFFENSE_CODE_GROUP  \
0           I182080058          2403               Disorderly Conduct   
166         I182079875          3801  Motor Vehicle Accident Response   
146         I182079895          3410                            Towed   
148         I182079893          1402                        Vandalism   
149         I182079892          1402                        Vandalism   
...                ...           ...                              ...   
327337      I152049637           802                   Simple Assault   
327338      I152049635          3831  Motor Vehicle Accident Response   
327339      I152049634          1842                   Drug Violation   
327340      I152049634          3125                  Warrant Arrests   
327308      I152049683           522             Residential Burglary   

                          OFFENSE_DESCRIPTION DISTRICT REPORTING_AREA  \
0                        DISTURBING THE PEACE      E18            495   
166                      M/V ACCIDENT - OTHER      D14            783   
146                       TOWED MOTOR VEHICLE       B2            237   
148                                 VANDALISM      C11            344   
149                                 VANDALISM      C11            368   
...                                       ...      ...            ...   
327337               ASSAULT SIMPLE - BATTERY      C11            817   
327338  M/V - LEAVING SCENE - PROPERTY DAMAGE       B2            602   
327339   DRUGS - POSS CLASS A - HEROIN, ETC.       E13            569   
327340                         WARRANT ARREST      E13            569   
327308      BURGLARY - RESIDENTIAL - NO FORCE       E5            686   

        SHOOTING  YEAR  MONTH  DAY_OF_WEEK  HOUR    UCR_PART  \
0              0  2018     10            6    20    Part Two   
166            0  2018     10            6    11  Part Three   
146            0  2018     10            6    11  Part Three   
148            0  2018     10            6    12    Part Two   
149            0  2018     10            6     7    Part Two   
...          ...   ...    ...          ...   ...         ...   
327337         0  2015      6            3    15    Part Two   
327338         0  2015      6            3    14  Part Three   
327339         0  2015      6            3    15    Part Two   
327340         0  2015      6            3    15  Part Three   
327308         0  2015      6            3    17    Part One   

                  STREET        Lat       Long                     Location  \
0           ARLINGTON ST  42.262608 -71.121186  (42.26260773, -71.12118637)   
166     COMMONWEALTH AVE  42.348886 -71.140074  (42.34888559, -71.14007361)   
146           EASTMAN ST  42.319860 -71.064341  (42.31986040, -71.06434120)   
148           BOWDOIN ST  42.300308 -71.072064  (42.30030819, -71.07206425)   
149         NEPONSET AVE  42.293836 -71.051574  (42.29383600, -71.05157448)   
...                  ...        ...        ...                          ...   
327337        TALBOT AVE  42.288638 -71.066316  (42.28863812, -71.06631579)   
327338        TREMONT ST  42.333669 -71.103335  (42.33366866, -71.10333486)   
327339       BROOKLEY RD  42.304816 -71.109118  (42.30481623, -71.10911850)   
327340       BROOKLEY RD  42.304816 -71.109118  (42.30481623, -71.10911850)   
327308       COLBERG AVE  42.283113 -71.143922  (42.28311294, -71.14392166)   

       OCCURRED_DAY  Summer  HOUR_12_16_17_18  
0        2018-10-03       0                 0  
166      2018-10-03       0                 0  
146      2018-10-03       0                 0  
148      2018-10-03       0                 1  
149      2018-10-03       0                 0  
...             ...     ...               ...  
327337   2015-06-15       1                 0  
327338   2015-06-15       1                 0  
327339   2015-06-15       1                 0  
327340   2015-06-15       1                 0  
327308 

In [15]:
def get_dummies(dataframe):
    
    #for DISTRICT column
    
    DISTRICT = pd.get_dummies(dataframe.DISTRICT, prefix = 'DIS')
    dataframe = pd.concat([dataframe,DISTRICT],axis = 1)
    dataframe = dataframe.drop(['DISTRICT'],axis = 1)
    
    #for UCR PART column
    
    UCR_PART = pd.get_dummies(dataframe.UCR_PART, prefix = 'UCR')
    dataframe = pd.concat([dataframe,UCR_PART],axis = 1)
    dataframe = dataframe.drop(['UCR_PART'],axis = 1)
    
    return dataframe
df_m_1 =get_dummies(df_m_1)
df_m_1

INCIDENT_NUMBER  OFFENSE_CODE               OFFENSE_CODE_GROUP  \
0           I182080058          2403               Disorderly Conduct   
166         I182079875          3801  Motor Vehicle Accident Response   
146         I182079895          3410                            Towed   
148         I182079893          1402                        Vandalism   
149         I182079892          1402                        Vandalism   
...                ...           ...                              ...   
327337      I152049637           802                   Simple Assault   
327338      I152049635          3831  Motor Vehicle Accident Response   
327339      I152049634          1842                   Drug Violation   
327340      I152049634          3125                  Warrant Arrests   
327308      I152049683           522             Residential Burglary   

                          OFFENSE_DESCRIPTION REPORTING_AREA  SHOOTING  YEAR  \
0                        DISTURBING THE PEACE            495         0  2018   
166                      M/V ACCIDENT - OTHER            783         0  2018   
146                       TOWED MOTOR VEHICLE            237         0  2018   
148                                 VANDALISM            344         0  2018   
149                                 VANDALISM            368         0  2018   
...                                       ...            ...       ...   ...   
327337               ASSAULT SIMPLE - BATTERY            817         0  2015   
327338  M/V - LEAVING SCENE - PROPERTY DAMAGE            602         0  2015   
327339   DRUGS - POSS CLASS A - HEROIN, ETC.             569         0  2015   
327340                         WARRANT ARREST            569         0  2015   
327308      BURGLARY - RESIDENTIAL - NO FORCE            686         0  2015   

        MONTH  DAY_OF_WEEK  HOUR  ... DIS_C6  DIS_D14  DIS_D4 DIS_E13 DIS_E18  \
0          10            6    20  ...      0        0       0       0       1   
166        10            6    11  ...      0        1       0       0       0   
146        10            6    11  ...      0        0       0       0       0   
148        10            6    12  ...      0        0       0       0       0   
149        10            6     7  ...      0        0       0       0       0   
...       ...          ...   ...  ...    ...      ...     ...     ...     ...   
327337      6            3    15  ...      0        0       0       0       0   
327338      6            3    14  ...      0        0       0       0       0   
327339      6            3    15  ...      0        0       0       1       0   
327340      6            3    15  ...      0        0       0       1       0   
327308      6            3    17  ...      0        0       0       0       0   

        DIS_E5  UCR_Other  UCR_Part One  UCR_Part Three  UCR_Part Two  
0            0          0             0               0             1  
166          0          0             0               1             0  
146          0          0             0               1             0  
148          0          0             0               0             1  
149          0          0             0               0             1  
...        ...        ...           ...             ...           ...  
327337       0          0             0               0             1  
327338       0          0             0               1             0  
327339       0          0             0               0             1  
327340       0          0             0               1             0  
327308       1          0             1               0             0  

[306413 rows x 33 columns]

In [16]:
df_m_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 306413 entries, 0 to 327308
Data columns (total 33 columns):
 #   Column               Non-Null Count   Dtype         
---  ------               --------------   -----         
 0   INCIDENT_NUMBER      306413 non-null  object        
 1   OFFENSE_CODE         306413 non-null  int64         
 2   OFFENSE_CODE_GROUP   306413 non-null  object        
 3   OFFENSE_DESCRIPTION  306413 non-null  object        
 4   REPORTING_AREA       306413 non-null  object        
 5   SHOOTING             306413 non-null  int64         
 6   YEAR                 306413 non-null  int64         
 7   MONTH                306413 non-null  int64         
 8   DAY_OF_WEEK          306413 non-null  int64         
 9   HOUR                 306413 non-null  int64         
 10  STREET               304631 non-null  object        
 11  Lat                  306413 non-null  float64       
 12  Long                 306413 non-null  float64       
 13  Location      

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
from sklearn.utils import shuffle
df_m_1 = shuffle(df_m_1)

In [19]:
df_m_1.columns

Index(['INCIDENT_NUMBER', 'OFFENSE_CODE', 'OFFENSE_CODE_GROUP',
       'OFFENSE_DESCRIPTION', 'REPORTING_AREA', 'SHOOTING', 'YEAR', 'MONTH',
       'DAY_OF_WEEK', 'HOUR', 'STREET', 'Lat', 'Long', 'Location',
       'OCCURRED_DAY', 'Summer', 'HOUR_12_16_17_18', 'DIS_A1', 'DIS_A15',
       'DIS_A7', 'DIS_B2', 'DIS_B3', 'DIS_C11', 'DIS_C6', 'DIS_D14', 'DIS_D4',
       'DIS_E13', 'DIS_E18', 'DIS_E5', 'UCR_Other', 'UCR_Part One',
       'UCR_Part Three', 'UCR_Part Two'],
      dtype='object')

In [57]:
train_set = df_m_1[['Lat','Long','Summer','HOUR_12_16_17_18','DIS_A1','DIS_A15','DIS_A7','DIS_B2','DIS_B3', 'DIS_C11', 'DIS_C6', 'DIS_D14', 'DIS_D4', 'DIS_E13', 'DIS_E18', 'DIS_E5','UCR_Part One']].head(int(len(df_m_1) *0.8))
train_set

Lat       Long  Summer  HOUR_12_16_17_18  DIS_A1  DIS_A15  \
189005  42.285260 -71.064441       0                 1       0        0   
152800  42.337635 -71.070130       0                 0       0        0   
71321   42.337314 -71.048523       0                 1       0        0   
117965  42.275313 -71.115878       1                 0       0        0   
6932    42.349020 -71.081301       1                 1       0        0   
...           ...        ...     ...               ...     ...      ...   
199570  42.279057 -71.095848       0                 1       0        0   
150087  42.271799 -71.072870       0                 0       0        0   
74906   42.335374 -71.078316       0                 0       0        0   
129936  42.297424 -71.076205       1                 0       0        0   
241601  42.300859 -71.081288       0                 0       0        0   

        DIS_A7  DIS_B2  DIS_B3  DIS_C11  DIS_C6  DIS_D14  DIS_D4  DIS_E13  \
189005       0       0       0        1       0        0       0        0   
152800       0       0       0        0       0        0       1        0   
71321        0       0       0        0       1        0       0        0   
117965       0       0       0        0       0        0       0        0   
6932         0       0       0        0       0        0       1        0   
...        ...     ...     ...      ...     ...      ...     ...      ...   
199570       0       0       1        0       0        0       0        0   
150087       0       0       1        0       0        0       0        0   
74906        0       0       0        0       0        0       1        0   
129936       0       0       1        0       0        0       0        0   
241601       0       0       1        0       0        0       0        0   

        DIS_E18  DIS_E5  UCR_Part One  
189005        0       0             0  
152800        0       0             0  
71321         0       0             0  
117965        1       0             1  
6932          0       0             1  
...         ...     ...           ...  
199570        0       0             0  
150087        0       0             0  
74906         0       0             0  
129936        0       0             1  
241601        0       0             1  

[245130 rows x 17 columns]

In [58]:
validation_set = df_m_1.tail(int(len(df_m_1) *0.2))[['Lat','Long','Summer','HOUR_12_16_17_18','DIS_A1','DIS_A15','DIS_A7','DIS_B2','DIS_B3', 'DIS_C11', 'DIS_C6', 'DIS_D14', 'DIS_D4', 'DIS_E13', 'DIS_E18', 'DIS_E5','UCR_Part One']]
validation_set


Lat       Long  Summer  HOUR_12_16_17_18  DIS_A1  DIS_A15  \
167488  42.311507 -71.074669       0                 1       0        0   
115854  42.335062 -71.093168       1                 0       0        0   
81070   42.267430 -71.109169       0                 0       0        0   
314425  42.379356 -71.030025       1                 0       0        0   
220548  42.287894 -71.124573       1                 0       0        0   
...           ...        ...     ...               ...     ...      ...   
37798   42.357546 -71.058820       0                 1       1        0   
55849   42.311905 -71.059105       0                 1       0        0   
185890  42.268174 -71.093877       0                 0       0        0   
304743  42.276266 -71.082650       1                 1       0        0   
156609  42.335117 -71.107677       0                 0       0        0   

        DIS_A7  DIS_B2  DIS_B3  DIS_C11  DIS_C6  DIS_D14  DIS_D4  DIS_E13  \
167488       0       1       0        0       0        0       0        0   
115854       0       1       0        0       0        0       0        0   
81070        0       0       0        0       0        0       0        0   
314425       1       0       0        0       0        0       0        0   
220548       0       0       0        0       0        0       0        0   
...        ...     ...     ...      ...     ...      ...     ...      ...   
37798        0       0       0        0       0        0       0        0   
55849        0       0       0        1       0        0       0        0   
185890       0       0       1        0       0        0       0        0   
304743       0       0       1        0       0        0       0        0   
156609       0       1       0        0       0        0       0        0   

        DIS_E18  DIS_E5  UCR_Part One  
167488        0       0             0  
115854        0       0             0  
81070         1       0             0  
314425        0       0             0  
220548        0       1             0  
...         ...     ...           ...  
37798         0       0             0  
55849         0       0             0  
185890        0       0             1  
304743        0       0             0  
156609        0       0             0  

[61282 rows x 17 columns]

In [59]:
groundTruth= validation_set['UCR_Part One'].to_frame()
groundTruth

UCR_Part One
167488             0
115854             0
81070              0
314425             0
220548             0
...              ...
37798              0
55849              0
185890             1
304743             0
156609             0

[61282 rows x 1 columns]

In [60]:
scaler = StandardScaler()
scaled_validation_set = scaler.fit_transform(validation_set)
scaled_validation_set = pd.DataFrame(data=scaled_validation_set, columns=['Lat','Long','Summer','HOUR_12_16_17_18','DIS_A1','DIS_A15','DIS_A7','DIS_B2','DIS_B3', 'DIS_C11', 'DIS_C6', 'DIS_D14', 'DIS_D4', 'DIS_E13', 'DIS_E18', 'DIS_E5', 'UCR_Part One'])
scaled_validation_set = scaled_validation_set.drop('UCR_Part One', axis=1)
scaled_validation_set

Lat      Long    Summer  HOUR_12_16_17_18    DIS_A1   DIS_A15  \
0     -0.333436  0.272033 -0.833233          1.507966 -0.345437 -0.146115   
1      0.403394 -0.349780  1.200145         -0.663145 -0.345437 -0.146115   
2     -1.712247 -0.887655 -0.833233         -0.663145 -0.345437 -0.146115   
3      1.788969  1.772740  1.200145         -0.663145 -0.345437 -0.146115   
4     -1.072099 -1.405445  1.200145         -0.663145 -0.345437 -0.146115   
...         ...       ...       ...               ...       ...       ...   
61277  1.106724  0.804822 -0.833233          1.507966  2.894888 -0.146115   
61278 -0.321002  0.795216 -0.833233          1.507966 -0.345437 -0.146115   
61279 -1.688959 -0.373612 -0.833233         -0.663145 -0.345437 -0.146115   
61280 -1.435844  0.003757  1.200145          1.507966 -0.345437 -0.146115   
61281  0.405094 -0.837492 -0.833233         -0.663145 -0.345437 -0.146115   

         DIS_A7    DIS_B2    DIS_B3   DIS_C11    DIS_C6   DIS_D14    DIS_D4  \
0     -0.213392  2.337011 -0.359365 -0.400283 -0.281582 -0.261593 -0.383548   
1     -0.213392  2.337011 -0.359365 -0.400283 -0.281582 -0.261593 -0.383548   
2     -0.213392 -0.427897 -0.359365 -0.400283 -0.281582 -0.261593 -0.383548   
3      4.686220 -0.427897 -0.359365 -0.400283 -0.281582 -0.261593 -0.383548   
4     -0.213392 -0.427897 -0.359365 -0.400283 -0.281582 -0.261593 -0.383548   
...         ...       ...       ...       ...       ...       ...       ...   
61277 -0.213392 -0.427897 -0.359365 -0.400283 -0.281582 -0.261593 -0.383548   
61278 -0.213392 -0.427897 -0.359365  2.498233 -0.281582 -0.261593 -0.383548   
61279 -0.213392 -0.427897  2.782684 -0.400283 -0.281582 -0.261593 -0.383548   
61280 -0.213392 -0.427897  2.782684 -0.400283 -0.281582 -0.261593 -0.383548   
61281 -0.213392  2.337011 -0.359365 -0.400283 -0.281582 -0.261593 -0.383548   

        DIS_E13   DIS_E18    DIS_E5  
0     -0.239939 -0.245704 -0.208369  
1     -0.239939 -0.245704 -0.208369  
2     -0.239939  4.069932 -0.208369  
3     -0.239939 -0.245704 -0.208369  
4     -0.239939 -0.245704  4.799183  
...         ...       ...       ...  
61277 -0.239939 -0.245704 -0.208369  
61278 -0.239939 -0.245704 -0.208369  
61279 -0.239939 -0.245704 -0.208369  
61280 -0.239939 -0.245704 -0.208369  
61281 -0.239939 -0.245704 -0.208369  

[61282 rows x 16 columns]

In [61]:
scaled_train_set = scaler.fit_transform(train_set)
scaled_train_set = pd.DataFrame(data=scaled_train_set, columns=['Lat','Long','Summer','HOUR_12_16_17_18','DIS_A1','DIS_A15','DIS_A7','DIS_B2','DIS_B3', 'DIS_C11', 'DIS_C6', 'DIS_D14', 'DIS_D4', 'DIS_E13', 'DIS_E18', 'DIS_E5', 'UCR_Part One'])
scaled_train_set

Lat      Long    Summer  HOUR_12_16_17_18    DIS_A1  DIS_A15  \
0      -1.164391  0.619333 -0.832806          1.517422 -0.347378 -0.14446   
1       0.481003  0.428035 -0.832806         -0.659012 -0.347378 -0.14446   
2       0.470942  1.154509 -0.832806          1.517422 -0.347378 -0.14446   
3      -1.476890 -1.110104  1.200760         -0.659012 -0.347378 -0.14446   
4       0.838672  0.052438  1.200760          1.517422 -0.347378 -0.14446   
...          ...       ...       ...               ...       ...      ...   
245125 -1.359263 -0.436649 -0.832806          1.517422 -0.347378 -0.14446   
245126 -1.587281  0.335904 -0.832806         -0.659012 -0.347378 -0.14446   
245127  0.409986  0.152826 -0.832806         -0.659012 -0.347378 -0.14446   
245128 -0.782260  0.223788  1.200760         -0.659012 -0.347378 -0.14446   
245129 -0.674331  0.052884 -0.832806         -0.659012 -0.347378 -0.14446   

          DIS_A7    DIS_B2    DIS_B3   DIS_C11    DIS_C6   DIS_D14    DIS_D4  \
0      -0.210702 -0.428302 -0.356208  2.506325 -0.281665 -0.261441 -0.386403   
1      -0.210702 -0.428302 -0.356208 -0.398991 -0.281665 -0.261441  2.587972   
2      -0.210702 -0.428302 -0.356208 -0.398991  3.550314 -0.261441 -0.386403   
3      -0.210702 -0.428302 -0.356208 -0.398991 -0.281665 -0.261441 -0.386403   
4      -0.210702 -0.428302 -0.356208 -0.398991 -0.281665 -0.261441  2.587972   
...          ...       ...       ...       ...       ...       ...       ...   
245125 -0.210702 -0.428302  2.807347 -0.398991 -0.281665 -0.261441 -0.386403   
245126 -0.210702 -0.428302  2.807347 -0.398991 -0.281665 -0.261441 -0.386403   
245127 -0.210702 -0.428302 -0.356208 -0.398991 -0.281665 -0.261441  2.587972   
245128 -0.210702 -0.428302  2.807347 -0.398991 -0.281665 -0.261441 -0.386403   
245129 -0.210702 -0.428302  2.807347 -0.398991 -0.281665 -0.261441 -0.386403   

         DIS_E13   DIS_E18    DIS_E5  UCR_Part One  
0      -0.243069 -0.242410 -0.211829     -0.495240  
1      -0.243069 -0.242410 -0.211829     -0.495240  
2      -0.243069 -0.242410 -0.211829     -0.495240  
3      -0.243069  4.125244 -0.211829      2.019222  
4      -0.243069 -0.242410 -0.211829      2.019222  
...          ...       ...       ...           ...  
245125 -0.243069 -0.242410 -0.211829     -0.495240  
245126 -0.243069 -0.242410 -0.211829     -0.495240  
245127 -0.243069 -0.242410 -0.211829     -0.495240  
245128 -0.243069 -0.242410 -0.211829      2.019222  
245129 -0.243069 -0.242410 -0.211829      2.019222  

[245130 rows x 17 columns]

In [62]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import BernoulliNB
from sklearn.tree import ExtraTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.semi_supervised import LabelSpreading
from sklearn.svm import LinearSVC
from sklearn.neighbors.nearest_centroid import NearestCentroid
from sklearn.ensemble import RandomForestClassifier
from lightgbm import LGBMClassifier

In [63]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

def classification_metrics(y_test, predict):
    print("Confusion Matrix:\n")
    print(confusion_matrix(y_test, predict))
    print("\nAccuracy: ", accuracy_score(y_test, predict))
    print("\nClassification report:\n")
    print(classification_report(y_test, predict))

In [64]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(scaled_train_set.drop(columns=["UCR_Part One"]), train_set["UCR_Part One"], random_state = 0, test_size = 0.33)  

### Random Forest

In [65]:
from sklearn.ensemble import RandomForestClassifier
rfC = RandomForestClassifier(criterion='entropy', max_depth= 8, max_leaf_nodes=5, min_samples_leaf=5, n_estimators= 100, class_weight='balanced', random_state=0)

rfC.fit(x_train, y_train)
predict = pd.DataFrame(data=rfC.predict(x_test))
classification_metrics(y_test, predict)

Confusion Matrix:

[[47070 17993]
 [ 9404  6426]]

Accuracy:  0.6613180374074394

Classification report:

              precision    recall  f1-score   support

           0       0.83      0.72      0.77     65063
           1       0.26      0.41      0.32     15830

    accuracy                           0.66     80893
   macro avg       0.55      0.56      0.55     80893
weighted avg       0.72      0.66      0.69     80893



### Random Forest Validation Test Score

In [66]:
predict = pd.DataFrame(data=rfC.predict(scaled_validation_set))
rfC_accuracy = classification_metrics(groundTruth, predict)
print('rfC_accuracy:', rfC_accuracy)

Confusion Matrix:

[[35543 13596]
 [ 7234  4909]]

Accuracy:  0.6600959498710878

Classification report:

              precision    recall  f1-score   support

           0       0.83      0.72      0.77     49139
           1       0.27      0.40      0.32     12143

    accuracy                           0.66     61282
   macro avg       0.55      0.56      0.55     61282
weighted avg       0.72      0.66      0.68     61282

rfC_accuracy: None


### ExtraTree Classifier 

In [67]:
from sklearn.ensemble import ExtraTreesClassifier
etC = ExtraTreesClassifier(random_state=0, n_estimators=50)

etC.fit(x_train, y_train)
predict = pd.DataFrame(data=etC.predict(x_test))
classification_metrics(y_test, predict)

Confusion Matrix:

[[61246  3817]
 [13460  2370]]

Accuracy:  0.7864215692334319

Classification report:

              precision    recall  f1-score   support

           0       0.82      0.94      0.88     65063
           1       0.38      0.15      0.22     15830

    accuracy                           0.79     80893
   macro avg       0.60      0.55      0.55     80893
weighted avg       0.73      0.79      0.75     80893



### ExtraTree Classifier Validation Test Score

In [68]:
predict = pd.DataFrame(data=etC.predict(scaled_validation_set))
etC_accuracy = classification_metrics(groundTruth, predict)
print('etC_accuracy:', etC_accuracy)

Confusion Matrix:

[[47139  2000]
 [10898  1245]]

Accuracy:  0.7895303678078391

Classification report:

              precision    recall  f1-score   support

           0       0.81      0.96      0.88     49139
           1       0.38      0.10      0.16     12143

    accuracy                           0.79     61282
   macro avg       0.60      0.53      0.52     61282
weighted avg       0.73      0.79      0.74     61282

etC_accuracy: None


### Ada Boosting

In [69]:
from sklearn.ensemble import AdaBoostClassifier

abC = AdaBoostClassifier(random_state=0, n_estimators=10, learning_rate=0.9)
abC.fit(x_train, y_train)
predict = pd.DataFrame(data=abC.predict(x_test), index = x_test.index)
classification_metrics(y_test, predict)



Confusion Matrix:

[[65063     0]
 [15830     0]]

Accuracy:  0.804309396363097

Classification report:

              precision    recall  f1-score   support

           0       0.80      1.00      0.89     65063
           1       0.00      0.00      0.00     15830

    accuracy                           0.80     80893
   macro avg       0.40      0.50      0.45     80893
weighted avg       0.65      0.80      0.72     80893



/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Ada Boosting Validation Test Score

In [70]:
predict = pd.DataFrame(data=abC.predict(scaled_validation_set))
abC_accuracy = classification_metrics(groundTruth, predict)
print('abC_accuracy:', abC_accuracy)

Confusion Matrix:

[[49139     0]
 [12143     0]]

Accuracy:  0.8018504617995497

Classification report:

              precision    recall  f1-score   support

           0       0.80      1.00      0.89     49139
           1       0.00      0.00      0.00     12143

    accuracy                           0.80     61282
   macro avg       0.40      0.50      0.45     61282
weighted avg       0.64      0.80      0.71     61282

abC_accuracy: None


/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Gradient Boosting

In [71]:
from sklearn.ensemble import GradientBoostingClassifier

gbC = GradientBoostingClassifier(random_state=0, n_estimators=10)
gbC.fit(x_train, y_train)
predict = pd.DataFrame(data=gbC.predict(x_test), index = x_test.index)
classification_metrics(y_test, predict)


Confusion Matrix:

[[65063     0]
 [15830     0]]

Accuracy:  0.804309396363097

Classification report:

              precision    recall  f1-score   support

           0       0.80      1.00      0.89     65063
           1       0.00      0.00      0.00     15830

    accuracy                           0.80     80893
   macro avg       0.40      0.50      0.45     80893
weighted avg       0.65      0.80      0.72     80893



/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Gradient Boosting Validation Test Score

In [72]:
predict = pd.DataFrame(data=gbC.predict(scaled_validation_set))
gbC_accuracy = classification_metrics(groundTruth, predict)
print('gbC_accuracy:', gbC_accuracy)


Confusion Matrix:

[[49139     0]
 [12143     0]]

Accuracy:  0.8018504617995497

Classification report:

              precision    recall  f1-score   support

           0       0.80      1.00      0.89     49139
           1       0.00      0.00      0.00     12143

    accuracy                           0.80     61282
   macro avg       0.40      0.50      0.45     61282
weighted avg       0.64      0.80      0.71     61282

gbC_accuracy: None


/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### XGBoost 

In [73]:
from xgboost import XGBClassifier

xgB = XGBClassifier(scale_pos_weight = 5,random_state=0)
xgB.fit(x_train, y_train)
predict = pd.DataFrame(data=xgB.predict(x_test))
classification_metrics(y_test, predict)


Confusion Matrix:

[[31957 33106]
 [ 4833 10997]]

Accuracy:  0.5309977377523395

Classification report:

              precision    recall  f1-score   support

           0       0.87      0.49      0.63     65063
           1       0.25      0.69      0.37     15830

    accuracy                           0.53     80893
   macro avg       0.56      0.59      0.50     80893
weighted avg       0.75      0.53      0.58     80893



In [74]:
# TP FP
# FN TN
 

### XGBoost Validation Test Score

In [75]:
predict = pd.DataFrame(data=xgB.predict(scaled_validation_set))
xgB_accuracy = classification_metrics(groundTruth, predict)
print('xgB_accuracy:', xgB_accuracy)

Confusion Matrix:

[[24156 24983]
 [ 4227  7916]]

Accuracy:  0.5233510655657453

Classification report:

              precision    recall  f1-score   support

           0       0.85      0.49      0.62     49139
           1       0.24      0.65      0.35     12143

    accuracy                           0.52     61282
   macro avg       0.55      0.57      0.49     61282
weighted avg       0.73      0.52      0.57     61282

xgB_accuracy: None


### KNeighbors Classifier

In [76]:
# knC = KNeighborsClassifier(n_neighbors=3)
# knC.fit(x_train, y_train) 
# knC_pred = knC.predict(x_test)

# classification_metrics(y_test, knC_pred)


### KNeigbors Classifier Validation Test Score

In [77]:
# predict = pd.DataFrame(data=knC.predict(scaled_validation_set))
# knC_accuracy = accuracy_score(groundTruth, predict)
# print('knC_accuracy:', knC_accuracy)

### LGBM Classifier

In [82]:
lgbm = LGBMClassifier(scale_pos_weight=4.5, random_state=0)
lgbm.fit(x_train, y_train)
lgbm_pred = lgbm.predict(x_test)

classification_metrics(y_test, lgbm_pred)

Confusion Matrix:

[[29301 35762]
 [ 4380 11450]]

Accuracy:  0.5037642317629462

Classification report:

              precision    recall  f1-score   support

           0       0.87      0.45      0.59     65063
           1       0.24      0.72      0.36     15830

    accuracy                           0.50     80893
   macro avg       0.56      0.59      0.48     80893
weighted avg       0.75      0.50      0.55     80893



### LGBM Classifier Validation Test Score

In [79]:
predict = pd.DataFrame(data=lgbm.predict(scaled_validation_set))
lgbm_accuracy = classification_metrics(groundTruth, predict)
print('lgbm_accuracy:', lgbm_accuracy)

Confusion Matrix:

[[35317 13822]
 [ 6547  5596]]

Accuracy:  0.6676185503084103

Classification report:

              precision    recall  f1-score   support

           0       0.84      0.72      0.78     49139
           1       0.29      0.46      0.35     12143

    accuracy                           0.67     61282
   macro avg       0.57      0.59      0.57     61282
weighted avg       0.73      0.67      0.69     61282

lgbm_accuracy: None


### Gaussian 

In [80]:
gauss = GaussianNB()
gauss = gauss.fit(x_train, y_train)
gauss_pred = gauss.predict(x_test)

classification_metrics(y_test, gauss_pred)

Confusion Matrix:

[[50959 14104]
 [10379  5451]]

Accuracy:  0.697340931848244

Classification report:

              precision    recall  f1-score   support

           0       0.83      0.78      0.81     65063
           1       0.28      0.34      0.31     15830

    accuracy                           0.70     80893
   macro avg       0.55      0.56      0.56     80893
weighted avg       0.72      0.70      0.71     80893



### Gaussian Validation Test Score

In [81]:
predict = pd.DataFrame(data=gauss.predict(scaled_validation_set))
gauss_accuracy = classification_metrics(groundTruth, predict)
    
print('gauss_accuracy:', gauss_accuracy)

Confusion Matrix:

[[38388 10751]
 [ 7983  4160]]

Accuracy:  0.6942984889527104

Classification report:

              precision    recall  f1-score   support

           0       0.83      0.78      0.80     49139
           1       0.28      0.34      0.31     12143

    accuracy                           0.69     61282
   macro avg       0.55      0.56      0.56     61282
weighted avg       0.72      0.69      0.71     61282

gauss_accuracy: None
